/* soap_collectorH.h
   Generated by gSOAP 2.6.0 from gsoap_collector.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#ifndef soap_collectorH_H
#define soap_collectorH_H
#include "soap_collectorStub.h"

SOAP_BEGIN_NAMESPACE(soap_collector)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putattachments(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getattachments(struct soap*);

#ifndef SOAP_TYPE_xsd__byte
#define SOAP_TYPE_xsd__byte (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_xsd__byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_xsd__byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_long(struct soap*, long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_long(struct soap*, long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_long(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_long(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_long(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__long(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__long(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__long(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_xsd__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_xsd__long(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_LONG64(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_xsd__float
#define SOAP_TYPE_xsd__float (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__float(struct soap*, float *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__float(struct soap*, float const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_xsd__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_xsd__float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_float(struct soap*, float const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedByte(struct soap*, unsigned char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedInt(struct soap*, unsigned int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_condor__ClassAdAttrType
#define SOAP_TYPE_condor__ClassAdAttrType (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__ClassAdAttrType(struct soap*, enum condor__ClassAdAttrType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__ClassAdAttrType(struct soap*, enum condor__ClassAdAttrType const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__ClassAdAttrType(struct soap*, const enum condor__ClassAdAttrType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__ClassAdAttrType(struct soap*, const char*, int, const enum condor__ClassAdAttrType *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_condor__ClassAdAttrType2s(struct soap*, enum condor__ClassAdAttrType);
SOAP_FMAC3 enum condor__ClassAdAttrType * SOAP_FMAC4 soap_get_condor__ClassAdAttrType(struct soap*, enum condor__ClassAdAttrType *, const char*, const char*);
SOAP_FMAC3 enum condor__ClassAdAttrType * SOAP_FMAC4 soap_in_condor__ClassAdAttrType(struct soap*, const char*, enum condor__ClassAdAttrType *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2condor__ClassAdAttrType(struct soap*, const char*, enum condor__ClassAdAttrType *);

#ifndef SOAP_TYPE_condor__StatusCode
#define SOAP_TYPE_condor__StatusCode (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__StatusCode(struct soap*, enum condor__StatusCode *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__StatusCode(struct soap*, enum condor__StatusCode const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__StatusCode(struct soap*, const enum condor__StatusCode *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__StatusCode(struct soap*, const char*, int, const enum condor__StatusCode *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_condor__StatusCode2s(struct soap*, enum condor__StatusCode);
SOAP_FMAC3 enum condor__StatusCode * SOAP_FMAC4 soap_get_condor__StatusCode(struct soap*, enum condor__StatusCode *, const char*, const char*);
SOAP_FMAC3 enum condor__StatusCode * SOAP_FMAC4 soap_in_condor__StatusCode(struct soap*, const char*, enum condor__StatusCode *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2condor__StatusCode(struct soap*, const char*, enum condor__StatusCode *);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__boolean(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_xsd__boolean2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2xsd__boolean(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_bool(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2bool(struct soap*, const char*, bool *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_condor__queryAnyAds
#define SOAP_TYPE_condor__queryAnyAds (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryAnyAds(struct soap*, struct condor__queryAnyAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryAnyAds(struct soap*, const struct condor__queryAnyAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryAnyAds(struct soap*, struct condor__queryAnyAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryAnyAds(struct soap*, const struct condor__queryAnyAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryAnyAds(struct soap*, const char*, int, const struct condor__queryAnyAds *, const char*);
SOAP_FMAC3 struct condor__queryAnyAds * SOAP_FMAC4 soap_get_condor__queryAnyAds(struct soap*, struct condor__queryAnyAds *, const char*, const char*);
SOAP_FMAC3 struct condor__queryAnyAds * SOAP_FMAC4 soap_in_condor__queryAnyAds(struct soap*, const char*, struct condor__queryAnyAds *, const char*);

#ifndef SOAP_TYPE_condor__queryAnyAdsResponse
#define SOAP_TYPE_condor__queryAnyAdsResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryAnyAdsResponse(struct soap*, struct condor__queryAnyAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryAnyAdsResponse(struct soap*, const struct condor__queryAnyAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryAnyAdsResponse(struct soap*, struct condor__queryAnyAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryAnyAdsResponse(struct soap*, const struct condor__queryAnyAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryAnyAdsResponse(struct soap*, const char*, int, const struct condor__queryAnyAdsResponse *, const char*);
SOAP_FMAC3 struct condor__queryAnyAdsResponse * SOAP_FMAC4 soap_get_condor__queryAnyAdsResponse(struct soap*, struct condor__queryAnyAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condor__queryAnyAdsResponse * SOAP_FMAC4 soap_in_condor__queryAnyAdsResponse(struct soap*, const char*, struct condor__queryAnyAdsResponse *, const char*);

#ifndef SOAP_TYPE_condor__queryStorageAds
#define SOAP_TYPE_condor__queryStorageAds (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryStorageAds(struct soap*, struct condor__queryStorageAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryStorageAds(struct soap*, const struct condor__queryStorageAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryStorageAds(struct soap*, struct condor__queryStorageAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryStorageAds(struct soap*, const struct condor__queryStorageAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryStorageAds(struct soap*, const char*, int, const struct condor__queryStorageAds *, const char*);
SOAP_FMAC3 struct condor__queryStorageAds * SOAP_FMAC4 soap_get_condor__queryStorageAds(struct soap*, struct condor__queryStorageAds *, const char*, const char*);
SOAP_FMAC3 struct condor__queryStorageAds * SOAP_FMAC4 soap_in_condor__queryStorageAds(struct soap*, const char*, struct condor__queryStorageAds *, const char*);

#ifndef SOAP_TYPE_condor__queryStorageAdsResponse
#define SOAP_TYPE_condor__queryStorageAdsResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryStorageAdsResponse(struct soap*, struct condor__queryStorageAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryStorageAdsResponse(struct soap*, const struct condor__queryStorageAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryStorageAdsResponse(struct soap*, struct condor__queryStorageAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryStorageAdsResponse(struct soap*, const struct condor__queryStorageAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryStorageAdsResponse(struct soap*, const char*, int, const struct condor__queryStorageAdsResponse *, const char*);
SOAP_FMAC3 struct condor__queryStorageAdsResponse * SOAP_FMAC4 soap_get_condor__queryStorageAdsResponse(struct soap*, struct condor__queryStorageAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condor__queryStorageAdsResponse * SOAP_FMAC4 soap_in_condor__queryStorageAdsResponse(struct soap*, const char*, struct condor__queryStorageAdsResponse *, const char*);

#ifndef SOAP_TYPE_condor__queryLicenseAds
#define SOAP_TYPE_condor__queryLicenseAds (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryLicenseAds(struct soap*, struct condor__queryLicenseAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryLicenseAds(struct soap*, const struct condor__queryLicenseAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryLicenseAds(struct soap*, struct condor__queryLicenseAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryLicenseAds(struct soap*, const struct condor__queryLicenseAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryLicenseAds(struct soap*, const char*, int, const struct condor__queryLicenseAds *, const char*);
SOAP_FMAC3 struct condor__queryLicenseAds * SOAP_FMAC4 soap_get_condor__queryLicenseAds(struct soap*, struct condor__queryLicenseAds *, const char*, const char*);
SOAP_FMAC3 struct condor__queryLicenseAds * SOAP_FMAC4 soap_in_condor__queryLicenseAds(struct soap*, const char*, struct condor__queryLicenseAds *, const char*);

#ifndef SOAP_TYPE_condor__queryLicenseAdsResponse
#define SOAP_TYPE_condor__queryLicenseAdsResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryLicenseAdsResponse(struct soap*, struct condor__queryLicenseAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryLicenseAdsResponse(struct soap*, const struct condor__queryLicenseAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryLicenseAdsResponse(struct soap*, struct condor__queryLicenseAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryLicenseAdsResponse(struct soap*, const struct condor__queryLicenseAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryLicenseAdsResponse(struct soap*, const char*, int, const struct condor__queryLicenseAdsResponse *, const char*);
SOAP_FMAC3 struct condor__queryLicenseAdsResponse * SOAP_FMAC4 soap_get_condor__queryLicenseAdsResponse(struct soap*, struct condor__queryLicenseAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condor__queryLicenseAdsResponse * SOAP_FMAC4 soap_in_condor__queryLicenseAdsResponse(struct soap*, const char*, struct condor__queryLicenseAdsResponse *, const char*);

#ifndef SOAP_TYPE_condor__querySubmittorAds
#define SOAP_TYPE_condor__querySubmittorAds (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__querySubmittorAds(struct soap*, struct condor__querySubmittorAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__querySubmittorAds(struct soap*, const struct condor__querySubmittorAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__querySubmittorAds(struct soap*, struct condor__querySubmittorAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__querySubmittorAds(struct soap*, const struct condor__querySubmittorAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__querySubmittorAds(struct soap*, const char*, int, const struct condor__querySubmittorAds *, const char*);
SOAP_FMAC3 struct condor__querySubmittorAds * SOAP_FMAC4 soap_get_condor__querySubmittorAds(struct soap*, struct condor__querySubmittorAds *, const char*, const char*);
SOAP_FMAC3 struct condor__querySubmittorAds * SOAP_FMAC4 soap_in_condor__querySubmittorAds(struct soap*, const char*, struct condor__querySubmittorAds *, const char*);

#ifndef SOAP_TYPE_condor__querySubmittorAdsResponse
#define SOAP_TYPE_condor__querySubmittorAdsResponse (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__querySubmittorAdsResponse(struct soap*, struct condor__querySubmittorAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__querySubmittorAdsResponse(struct soap*, const struct condor__querySubmittorAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__querySubmittorAdsResponse(struct soap*, struct condor__querySubmittorAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__querySubmittorAdsResponse(struct soap*, const struct condor__querySubmittorAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__querySubmittorAdsResponse(struct soap*, const char*, int, const struct condor__querySubmittorAdsResponse *, const char*);
SOAP_FMAC3 struct condor__querySubmittorAdsResponse * SOAP_FMAC4 soap_get_condor__querySubmittorAdsResponse(struct soap*, struct condor__querySubmittorAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condor__querySubmittorAdsResponse * SOAP_FMAC4 soap_in_condor__querySubmittorAdsResponse(struct soap*, const char*, struct condor__querySubmittorAdsResponse *, const char*);

#ifndef SOAP_TYPE_condor__queryMasterAds
#define SOAP_TYPE_condor__queryMasterAds (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryMasterAds(struct soap*, struct condor__queryMasterAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryMasterAds(struct soap*, const struct condor__queryMasterAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryMasterAds(struct soap*, struct condor__queryMasterAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryMasterAds(struct soap*, const struct condor__queryMasterAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryMasterAds(struct soap*, const char*, int, const struct condor__queryMasterAds *, const char*);
SOAP_FMAC3 struct condor__queryMasterAds * SOAP_FMAC4 soap_get_condor__queryMasterAds(struct soap*, struct condor__queryMasterAds *, const char*, const char*);
SOAP_FMAC3 struct condor__queryMasterAds * SOAP_FMAC4 soap_in_condor__queryMasterAds(struct soap*, const char*, struct condor__queryMasterAds *, const char*);

#ifndef SOAP_TYPE_condor__queryMasterAdsResponse
#define SOAP_TYPE_condor__queryMasterAdsResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryMasterAdsResponse(struct soap*, struct condor__queryMasterAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryMasterAdsResponse(struct soap*, const struct condor__queryMasterAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryMasterAdsResponse(struct soap*, struct condor__queryMasterAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryMasterAdsResponse(struct soap*, const struct condor__queryMasterAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryMasterAdsResponse(struct soap*, const char*, int, const struct condor__queryMasterAdsResponse *, const char*);
SOAP_FMAC3 struct condor__queryMasterAdsResponse * SOAP_FMAC4 soap_get_condor__queryMasterAdsResponse(struct soap*, struct condor__queryMasterAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condor__queryMasterAdsResponse * SOAP_FMAC4 soap_in_condor__queryMasterAdsResponse(struct soap*, const char*, struct condor__queryMasterAdsResponse *, const char*);

#ifndef SOAP_TYPE_condor__queryScheddAds
#define SOAP_TYPE_condor__queryScheddAds (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryScheddAds(struct soap*, struct condor__queryScheddAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryScheddAds(struct soap*, const struct condor__queryScheddAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryScheddAds(struct soap*, struct condor__queryScheddAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryScheddAds(struct soap*, const struct condor__queryScheddAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryScheddAds(struct soap*, const char*, int, const struct condor__queryScheddAds *, const char*);
SOAP_FMAC3 struct condor__queryScheddAds * SOAP_FMAC4 soap_get_condor__queryScheddAds(struct soap*, struct condor__queryScheddAds *, const char*, const char*);
SOAP_FMAC3 struct condor__queryScheddAds * SOAP_FMAC4 soap_in_condor__queryScheddAds(struct soap*, const char*, struct condor__queryScheddAds *, const char*);

#ifndef SOAP_TYPE_condor__queryScheddAdsResponse
#define SOAP_TYPE_condor__queryScheddAdsResponse (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryScheddAdsResponse(struct soap*, struct condor__queryScheddAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryScheddAdsResponse(struct soap*, const struct condor__queryScheddAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryScheddAdsResponse(struct soap*, struct condor__queryScheddAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryScheddAdsResponse(struct soap*, const struct condor__queryScheddAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryScheddAdsResponse(struct soap*, const char*, int, const struct condor__queryScheddAdsResponse *, const char*);
SOAP_FMAC3 struct condor__queryScheddAdsResponse * SOAP_FMAC4 soap_get_condor__queryScheddAdsResponse(struct soap*, struct condor__queryScheddAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condor__queryScheddAdsResponse * SOAP_FMAC4 soap_in_condor__queryScheddAdsResponse(struct soap*, const char*, struct condor__queryScheddAdsResponse *, const char*);

#ifndef SOAP_TYPE_condor__queryStartdAds
#define SOAP_TYPE_condor__queryStartdAds (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryStartdAds(struct soap*, struct condor__queryStartdAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryStartdAds(struct soap*, const struct condor__queryStartdAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryStartdAds(struct soap*, struct condor__queryStartdAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryStartdAds(struct soap*, const struct condor__queryStartdAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryStartdAds(struct soap*, const char*, int, const struct condor__queryStartdAds *, const char*);
SOAP_FMAC3 struct condor__queryStartdAds * SOAP_FMAC4 soap_get_condor__queryStartdAds(struct soap*, struct condor__queryStartdAds *, const char*, const char*);
SOAP_FMAC3 struct condor__queryStartdAds * SOAP_FMAC4 soap_in_condor__queryStartdAds(struct soap*, const char*, struct condor__queryStartdAds *, const char*);

#ifndef SOAP_TYPE_condor__queryStartdAdsResponse
#define SOAP_TYPE_condor__queryStartdAdsResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__queryStartdAdsResponse(struct soap*, struct condor__queryStartdAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__queryStartdAdsResponse(struct soap*, const struct condor__queryStartdAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__queryStartdAdsResponse(struct soap*, struct condor__queryStartdAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__queryStartdAdsResponse(struct soap*, const struct condor__queryStartdAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__queryStartdAdsResponse(struct soap*, const char*, int, const struct condor__queryStartdAdsResponse *, const char*);
SOAP_FMAC3 struct condor__queryStartdAdsResponse * SOAP_FMAC4 soap_get_condor__queryStartdAdsResponse(struct soap*, struct condor__queryStartdAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condor__queryStartdAdsResponse * SOAP_FMAC4 soap_in_condor__queryStartdAdsResponse(struct soap*, const char*, struct condor__queryStartdAdsResponse *, const char*);

#ifndef SOAP_TYPE_condor__StringAndStatus
#define SOAP_TYPE_condor__StringAndStatus (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__StringAndStatus(struct soap*, struct condor__StringAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__StringAndStatus(struct soap*, const struct condor__StringAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__StringAndStatus(struct soap*, struct condor__StringAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__StringAndStatus(struct soap*, const struct condor__StringAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__StringAndStatus(struct soap*, const char*, int, const struct condor__StringAndStatus *, const char*);
SOAP_FMAC3 struct condor__StringAndStatus * SOAP_FMAC4 soap_get_condor__StringAndStatus(struct soap*, struct condor__StringAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condor__StringAndStatus * SOAP_FMAC4 soap_in_condor__StringAndStatus(struct soap*, const char*, struct condor__StringAndStatus *, const char*);

#ifndef SOAP_TYPE_condor__ClassAdStructArrayAndStatus
#define SOAP_TYPE_condor__ClassAdStructArrayAndStatus (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__ClassAdStructArrayAndStatus(struct soap*, struct condor__ClassAdStructArrayAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__ClassAdStructArrayAndStatus(struct soap*, const struct condor__ClassAdStructArrayAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__ClassAdStructArrayAndStatus(struct soap*, struct condor__ClassAdStructArrayAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__ClassAdStructArrayAndStatus(struct soap*, const struct condor__ClassAdStructArrayAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__ClassAdStructArrayAndStatus(struct soap*, const char*, int, const struct condor__ClassAdStructArrayAndStatus *, const char*);
SOAP_FMAC3 struct condor__ClassAdStructArrayAndStatus * SOAP_FMAC4 soap_get_condor__ClassAdStructArrayAndStatus(struct soap*, struct condor__ClassAdStructArrayAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condor__ClassAdStructArrayAndStatus * SOAP_FMAC4 soap_in_condor__ClassAdStructArrayAndStatus(struct soap*, const char*, struct condor__ClassAdStructArrayAndStatus *, const char*);

#ifndef SOAP_TYPE_condor__ClassAdStructAndStatus
#define SOAP_TYPE_condor__ClassAdStructAndStatus (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__ClassAdStructAndStatus(struct soap*, struct condor__ClassAdStructAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__ClassAdStructAndStatus(struct soap*, const struct condor__ClassAdStructAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__ClassAdStructAndStatus(struct soap*, struct condor__ClassAdStructAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__ClassAdStructAndStatus(struct soap*, const struct condor__ClassAdStructAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__ClassAdStructAndStatus(struct soap*, const char*, int, const struct condor__ClassAdStructAndStatus *, const char*);
SOAP_FMAC3 struct condor__ClassAdStructAndStatus * SOAP_FMAC4 soap_get_condor__ClassAdStructAndStatus(struct soap*, struct condor__ClassAdStructAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condor__ClassAdStructAndStatus * SOAP_FMAC4 soap_in_condor__ClassAdStructAndStatus(struct soap*, const char*, struct condor__ClassAdStructAndStatus *, const char*);

#ifndef SOAP_TYPE_ClassAdStructArray
#define SOAP_TYPE_ClassAdStructArray (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ClassAdStructArray(struct soap*, struct ClassAdStructArray const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ClassAdStructArray(struct soap*, struct ClassAdStructArray const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ClassAdStructArray(struct soap*, struct ClassAdStructArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ClassAdStructArray(struct soap*, const struct ClassAdStructArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ClassAdStructArray(struct soap*, const char*, int, const struct ClassAdStructArray *, const char*);
SOAP_FMAC3 struct ClassAdStructArray * SOAP_FMAC4 soap_get_ClassAdStructArray(struct soap*, struct ClassAdStructArray *, const char*, const char*);
SOAP_FMAC3 struct ClassAdStructArray * SOAP_FMAC4 soap_in_ClassAdStructArray(struct soap*, const char*, struct ClassAdStructArray *, const char*);

#ifndef SOAP_TYPE_ClassAdStruct
#define SOAP_TYPE_ClassAdStruct (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ClassAdStruct(struct soap*, struct ClassAdStruct const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ClassAdStruct(struct soap*, struct ClassAdStruct const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ClassAdStruct(struct soap*, struct ClassAdStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ClassAdStruct(struct soap*, const struct ClassAdStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ClassAdStruct(struct soap*, const char*, int, const struct ClassAdStruct *, const char*);
SOAP_FMAC3 struct ClassAdStruct * SOAP_FMAC4 soap_get_ClassAdStruct(struct soap*, struct ClassAdStruct *, const char*, const char*);
SOAP_FMAC3 struct ClassAdStruct * SOAP_FMAC4 soap_in_ClassAdStruct(struct soap*, const char*, struct ClassAdStruct *, const char*);

#ifndef SOAP_TYPE_condor__ClassAdStructAttr
#define SOAP_TYPE_condor__ClassAdStructAttr (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__ClassAdStructAttr(struct soap*, struct condor__ClassAdStructAttr const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__ClassAdStructAttr(struct soap*, const struct condor__ClassAdStructAttr *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__ClassAdStructAttr(struct soap*, struct condor__ClassAdStructAttr *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__ClassAdStructAttr(struct soap*, const struct condor__ClassAdStructAttr *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__ClassAdStructAttr(struct soap*, const char*, int, const struct condor__ClassAdStructAttr *, const char*);
SOAP_FMAC3 struct condor__ClassAdStructAttr * SOAP_FMAC4 soap_get_condor__ClassAdStructAttr(struct soap*, struct condor__ClassAdStructAttr *, const char*, const char*);
SOAP_FMAC3 struct condor__ClassAdStructAttr * SOAP_FMAC4 soap_in_condor__ClassAdStructAttr(struct soap*, const char*, struct condor__ClassAdStructAttr *, const char*);

#ifndef SOAP_TYPE_condor__Status
#define SOAP_TYPE_condor__Status (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condor__Status(struct soap*, struct condor__Status const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condor__Status(struct soap*, const struct condor__Status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condor__Status(struct soap*, struct condor__Status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condor__Status(struct soap*, const struct condor__Status *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condor__Status(struct soap*, const char*, int, const struct condor__Status *, const char*);
SOAP_FMAC3 struct condor__Status * SOAP_FMAC4 soap_get_condor__Status(struct soap*, struct condor__Status *, const char*, const char*);
SOAP_FMAC3 struct condor__Status * SOAP_FMAC4 soap_in_condor__Status(struct soap*, const char*, struct condor__Status *, const char*);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToClassAdStruct
#define SOAP_TYPE_PointerToClassAdStruct (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToClassAdStruct(struct soap*, struct ClassAdStruct *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToClassAdStruct(struct soap*, struct ClassAdStruct *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToClassAdStruct(struct soap*, struct ClassAdStruct **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToClassAdStruct(struct soap*, struct ClassAdStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToClassAdStruct(struct soap*, const char *, int, struct ClassAdStruct *const*, const char *);
SOAP_FMAC3 struct ClassAdStruct ** SOAP_FMAC4 soap_get_PointerToClassAdStruct(struct soap*, struct ClassAdStruct **, const char*, const char*);
SOAP_FMAC3 struct ClassAdStruct ** SOAP_FMAC4 soap_in_PointerToClassAdStruct(struct soap*, const char*, struct ClassAdStruct **, const char*);

#ifndef SOAP_TYPE_PointerTocondor__ClassAdStructAttr
#define SOAP_TYPE_PointerTocondor__ClassAdStructAttr (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocondor__ClassAdStructAttr(struct soap*, struct condor__ClassAdStructAttr *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTocondor__ClassAdStructAttr(struct soap*, struct condor__ClassAdStructAttr *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTocondor__ClassAdStructAttr(struct soap*, struct condor__ClassAdStructAttr **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocondor__ClassAdStructAttr(struct soap*, struct condor__ClassAdStructAttr *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocondor__ClassAdStructAttr(struct soap*, const char *, int, struct condor__ClassAdStructAttr *const*, const char *);
SOAP_FMAC3 struct condor__ClassAdStructAttr ** SOAP_FMAC4 soap_get_PointerTocondor__ClassAdStructAttr(struct soap*, struct condor__ClassAdStructAttr **, const char*, const char*);
SOAP_FMAC3 struct condor__ClassAdStructAttr ** SOAP_FMAC4 soap_in_PointerTocondor__ClassAdStructAttr(struct soap*, const char*, struct condor__ClassAdStructAttr **, const char*);

#ifndef SOAP_TYPE_PointerTocondor__Status
#define SOAP_TYPE_PointerTocondor__Status (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocondor__Status(struct soap*, struct condor__Status *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTocondor__Status(struct soap*, struct condor__Status *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTocondor__Status(struct soap*, struct condor__Status **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocondor__Status(struct soap*, struct condor__Status *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocondor__Status(struct soap*, const char *, int, struct condor__Status *const*, const char *);
SOAP_FMAC3 struct condor__Status ** SOAP_FMAC4 soap_get_PointerTocondor__Status(struct soap*, struct condor__Status **, const char*, const char*);
SOAP_FMAC3 struct condor__Status ** SOAP_FMAC4 soap_in_PointerTocondor__Status(struct soap*, const char*, struct condor__Status **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTounsignedByte(struct soap*, unsigned char **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anyURI(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(soap_collector)

#endif

/* end of soap_collectorH.h */
