/* soap_collectorH.h
   Generated by gSOAP 2.3 rev 7 from gsoap_collector.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#ifndef soap_collectorH_H
#define soap_collectorH_H
#include "soap_collectorStub.h"

SOAP_BEGIN_NAMESPACE(soap_collector)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putattachments(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getattachments(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (0)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__int(struct soap*, long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_xsd__int(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_long(struct soap*, long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_long(struct soap*, long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_long(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_long(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_LONG64(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_xsd__float
#define SOAP_TYPE_xsd__float (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__float(struct soap*, float *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__float(struct soap*, float const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_xsd__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_xsd__float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_float(struct soap*, float const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedInt(struct soap*, unsigned int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_xsd__positiveInteger
#define SOAP_TYPE_xsd__positiveInteger (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__positiveInteger(struct soap*, ULONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__positiveInteger(struct soap*, ULONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__positiveInteger(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__positiveInteger(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get_xsd__positiveInteger(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in_xsd__positiveInteger(struct soap*, const char*, ULONG64 *, const char*);

#ifndef SOAP_TYPE_unsignedLONG64
#define SOAP_TYPE_unsignedLONG64 (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLONG64(struct soap*, ULONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedLONG64(struct soap*, ULONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLONG64(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLONG64(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get_unsignedLONG64(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in_unsignedLONG64(struct soap*, const char*, ULONG64 *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__boolean(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_xsd__boolean2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2xsd__boolean(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_bool(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2bool(struct soap*, const char*, bool *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_condorCollector__queryAnyAds
#define SOAP_TYPE_condorCollector__queryAnyAds (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryAnyAds(struct soap*, struct condorCollector__queryAnyAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryAnyAds(struct soap*, const struct condorCollector__queryAnyAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryAnyAds(struct soap*, struct condorCollector__queryAnyAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryAnyAds(struct soap*, struct condorCollector__queryAnyAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryAnyAds(struct soap*, const char*, int, const struct condorCollector__queryAnyAds *, const char*);
SOAP_FMAC3 struct condorCollector__queryAnyAds * SOAP_FMAC4 soap_get_condorCollector__queryAnyAds(struct soap*, struct condorCollector__queryAnyAds *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryAnyAds * SOAP_FMAC4 soap_in_condorCollector__queryAnyAds(struct soap*, const char*, struct condorCollector__queryAnyAds *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryAnyAdsResponse
#define SOAP_TYPE_condorCollector__queryAnyAdsResponse (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryAnyAdsResponse(struct soap*, struct condorCollector__queryAnyAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryAnyAdsResponse(struct soap*, const struct condorCollector__queryAnyAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryAnyAdsResponse(struct soap*, struct condorCollector__queryAnyAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryAnyAdsResponse(struct soap*, struct condorCollector__queryAnyAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryAnyAdsResponse(struct soap*, const char*, int, const struct condorCollector__queryAnyAdsResponse *, const char*);
SOAP_FMAC3 struct condorCollector__queryAnyAdsResponse * SOAP_FMAC4 soap_get_condorCollector__queryAnyAdsResponse(struct soap*, struct condorCollector__queryAnyAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryAnyAdsResponse * SOAP_FMAC4 soap_in_condorCollector__queryAnyAdsResponse(struct soap*, const char*, struct condorCollector__queryAnyAdsResponse *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryStorageAds
#define SOAP_TYPE_condorCollector__queryStorageAds (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryStorageAds(struct soap*, struct condorCollector__queryStorageAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryStorageAds(struct soap*, const struct condorCollector__queryStorageAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryStorageAds(struct soap*, struct condorCollector__queryStorageAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryStorageAds(struct soap*, struct condorCollector__queryStorageAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryStorageAds(struct soap*, const char*, int, const struct condorCollector__queryStorageAds *, const char*);
SOAP_FMAC3 struct condorCollector__queryStorageAds * SOAP_FMAC4 soap_get_condorCollector__queryStorageAds(struct soap*, struct condorCollector__queryStorageAds *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryStorageAds * SOAP_FMAC4 soap_in_condorCollector__queryStorageAds(struct soap*, const char*, struct condorCollector__queryStorageAds *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryStorageAdsResponse
#define SOAP_TYPE_condorCollector__queryStorageAdsResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryStorageAdsResponse(struct soap*, struct condorCollector__queryStorageAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryStorageAdsResponse(struct soap*, const struct condorCollector__queryStorageAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryStorageAdsResponse(struct soap*, struct condorCollector__queryStorageAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryStorageAdsResponse(struct soap*, struct condorCollector__queryStorageAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryStorageAdsResponse(struct soap*, const char*, int, const struct condorCollector__queryStorageAdsResponse *, const char*);
SOAP_FMAC3 struct condorCollector__queryStorageAdsResponse * SOAP_FMAC4 soap_get_condorCollector__queryStorageAdsResponse(struct soap*, struct condorCollector__queryStorageAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryStorageAdsResponse * SOAP_FMAC4 soap_in_condorCollector__queryStorageAdsResponse(struct soap*, const char*, struct condorCollector__queryStorageAdsResponse *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryLicenseAds
#define SOAP_TYPE_condorCollector__queryLicenseAds (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryLicenseAds(struct soap*, struct condorCollector__queryLicenseAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryLicenseAds(struct soap*, const struct condorCollector__queryLicenseAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryLicenseAds(struct soap*, struct condorCollector__queryLicenseAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryLicenseAds(struct soap*, struct condorCollector__queryLicenseAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryLicenseAds(struct soap*, const char*, int, const struct condorCollector__queryLicenseAds *, const char*);
SOAP_FMAC3 struct condorCollector__queryLicenseAds * SOAP_FMAC4 soap_get_condorCollector__queryLicenseAds(struct soap*, struct condorCollector__queryLicenseAds *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryLicenseAds * SOAP_FMAC4 soap_in_condorCollector__queryLicenseAds(struct soap*, const char*, struct condorCollector__queryLicenseAds *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryLicenseAdsResponse
#define SOAP_TYPE_condorCollector__queryLicenseAdsResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryLicenseAdsResponse(struct soap*, struct condorCollector__queryLicenseAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryLicenseAdsResponse(struct soap*, const struct condorCollector__queryLicenseAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryLicenseAdsResponse(struct soap*, struct condorCollector__queryLicenseAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryLicenseAdsResponse(struct soap*, struct condorCollector__queryLicenseAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryLicenseAdsResponse(struct soap*, const char*, int, const struct condorCollector__queryLicenseAdsResponse *, const char*);
SOAP_FMAC3 struct condorCollector__queryLicenseAdsResponse * SOAP_FMAC4 soap_get_condorCollector__queryLicenseAdsResponse(struct soap*, struct condorCollector__queryLicenseAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryLicenseAdsResponse * SOAP_FMAC4 soap_in_condorCollector__queryLicenseAdsResponse(struct soap*, const char*, struct condorCollector__queryLicenseAdsResponse *, const char*);

#ifndef SOAP_TYPE_condorCollector__querySubmittorAds
#define SOAP_TYPE_condorCollector__querySubmittorAds (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__querySubmittorAds(struct soap*, struct condorCollector__querySubmittorAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__querySubmittorAds(struct soap*, const struct condorCollector__querySubmittorAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__querySubmittorAds(struct soap*, struct condorCollector__querySubmittorAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__querySubmittorAds(struct soap*, struct condorCollector__querySubmittorAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__querySubmittorAds(struct soap*, const char*, int, const struct condorCollector__querySubmittorAds *, const char*);
SOAP_FMAC3 struct condorCollector__querySubmittorAds * SOAP_FMAC4 soap_get_condorCollector__querySubmittorAds(struct soap*, struct condorCollector__querySubmittorAds *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__querySubmittorAds * SOAP_FMAC4 soap_in_condorCollector__querySubmittorAds(struct soap*, const char*, struct condorCollector__querySubmittorAds *, const char*);

#ifndef SOAP_TYPE_condorCollector__querySubmittorAdsResponse
#define SOAP_TYPE_condorCollector__querySubmittorAdsResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__querySubmittorAdsResponse(struct soap*, struct condorCollector__querySubmittorAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__querySubmittorAdsResponse(struct soap*, const struct condorCollector__querySubmittorAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__querySubmittorAdsResponse(struct soap*, struct condorCollector__querySubmittorAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__querySubmittorAdsResponse(struct soap*, struct condorCollector__querySubmittorAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__querySubmittorAdsResponse(struct soap*, const char*, int, const struct condorCollector__querySubmittorAdsResponse *, const char*);
SOAP_FMAC3 struct condorCollector__querySubmittorAdsResponse * SOAP_FMAC4 soap_get_condorCollector__querySubmittorAdsResponse(struct soap*, struct condorCollector__querySubmittorAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__querySubmittorAdsResponse * SOAP_FMAC4 soap_in_condorCollector__querySubmittorAdsResponse(struct soap*, const char*, struct condorCollector__querySubmittorAdsResponse *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryMasterAds
#define SOAP_TYPE_condorCollector__queryMasterAds (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryMasterAds(struct soap*, struct condorCollector__queryMasterAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryMasterAds(struct soap*, const struct condorCollector__queryMasterAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryMasterAds(struct soap*, struct condorCollector__queryMasterAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryMasterAds(struct soap*, struct condorCollector__queryMasterAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryMasterAds(struct soap*, const char*, int, const struct condorCollector__queryMasterAds *, const char*);
SOAP_FMAC3 struct condorCollector__queryMasterAds * SOAP_FMAC4 soap_get_condorCollector__queryMasterAds(struct soap*, struct condorCollector__queryMasterAds *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryMasterAds * SOAP_FMAC4 soap_in_condorCollector__queryMasterAds(struct soap*, const char*, struct condorCollector__queryMasterAds *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryMasterAdsResponse
#define SOAP_TYPE_condorCollector__queryMasterAdsResponse (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryMasterAdsResponse(struct soap*, struct condorCollector__queryMasterAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryMasterAdsResponse(struct soap*, const struct condorCollector__queryMasterAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryMasterAdsResponse(struct soap*, struct condorCollector__queryMasterAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryMasterAdsResponse(struct soap*, struct condorCollector__queryMasterAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryMasterAdsResponse(struct soap*, const char*, int, const struct condorCollector__queryMasterAdsResponse *, const char*);
SOAP_FMAC3 struct condorCollector__queryMasterAdsResponse * SOAP_FMAC4 soap_get_condorCollector__queryMasterAdsResponse(struct soap*, struct condorCollector__queryMasterAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryMasterAdsResponse * SOAP_FMAC4 soap_in_condorCollector__queryMasterAdsResponse(struct soap*, const char*, struct condorCollector__queryMasterAdsResponse *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryScheddAds
#define SOAP_TYPE_condorCollector__queryScheddAds (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryScheddAds(struct soap*, struct condorCollector__queryScheddAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryScheddAds(struct soap*, const struct condorCollector__queryScheddAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryScheddAds(struct soap*, struct condorCollector__queryScheddAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryScheddAds(struct soap*, struct condorCollector__queryScheddAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryScheddAds(struct soap*, const char*, int, const struct condorCollector__queryScheddAds *, const char*);
SOAP_FMAC3 struct condorCollector__queryScheddAds * SOAP_FMAC4 soap_get_condorCollector__queryScheddAds(struct soap*, struct condorCollector__queryScheddAds *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryScheddAds * SOAP_FMAC4 soap_in_condorCollector__queryScheddAds(struct soap*, const char*, struct condorCollector__queryScheddAds *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryScheddAdsResponse
#define SOAP_TYPE_condorCollector__queryScheddAdsResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryScheddAdsResponse(struct soap*, struct condorCollector__queryScheddAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryScheddAdsResponse(struct soap*, const struct condorCollector__queryScheddAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryScheddAdsResponse(struct soap*, struct condorCollector__queryScheddAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryScheddAdsResponse(struct soap*, struct condorCollector__queryScheddAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryScheddAdsResponse(struct soap*, const char*, int, const struct condorCollector__queryScheddAdsResponse *, const char*);
SOAP_FMAC3 struct condorCollector__queryScheddAdsResponse * SOAP_FMAC4 soap_get_condorCollector__queryScheddAdsResponse(struct soap*, struct condorCollector__queryScheddAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryScheddAdsResponse * SOAP_FMAC4 soap_in_condorCollector__queryScheddAdsResponse(struct soap*, const char*, struct condorCollector__queryScheddAdsResponse *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryStartdAds
#define SOAP_TYPE_condorCollector__queryStartdAds (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryStartdAds(struct soap*, struct condorCollector__queryStartdAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryStartdAds(struct soap*, const struct condorCollector__queryStartdAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryStartdAds(struct soap*, struct condorCollector__queryStartdAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryStartdAds(struct soap*, struct condorCollector__queryStartdAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryStartdAds(struct soap*, const char*, int, const struct condorCollector__queryStartdAds *, const char*);
SOAP_FMAC3 struct condorCollector__queryStartdAds * SOAP_FMAC4 soap_get_condorCollector__queryStartdAds(struct soap*, struct condorCollector__queryStartdAds *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryStartdAds * SOAP_FMAC4 soap_in_condorCollector__queryStartdAds(struct soap*, const char*, struct condorCollector__queryStartdAds *, const char*);

#ifndef SOAP_TYPE_condorCollector__queryStartdAdsResponse
#define SOAP_TYPE_condorCollector__queryStartdAdsResponse (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCollector__queryStartdAdsResponse(struct soap*, struct condorCollector__queryStartdAdsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCollector__queryStartdAdsResponse(struct soap*, const struct condorCollector__queryStartdAdsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCollector__queryStartdAdsResponse(struct soap*, struct condorCollector__queryStartdAdsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCollector__queryStartdAdsResponse(struct soap*, struct condorCollector__queryStartdAdsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCollector__queryStartdAdsResponse(struct soap*, const char*, int, const struct condorCollector__queryStartdAdsResponse *, const char*);
SOAP_FMAC3 struct condorCollector__queryStartdAdsResponse * SOAP_FMAC4 soap_get_condorCollector__queryStartdAdsResponse(struct soap*, struct condorCollector__queryStartdAdsResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCollector__queryStartdAdsResponse * SOAP_FMAC4 soap_in_condorCollector__queryStartdAdsResponse(struct soap*, const char*, struct condorCollector__queryStartdAdsResponse *, const char*);

#ifndef SOAP_TYPE_condorCore__getPlatformString
#define SOAP_TYPE_condorCore__getPlatformString (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__getPlatformString(struct soap*, struct condorCore__getPlatformString const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__getPlatformString(struct soap*, const struct condorCore__getPlatformString *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__getPlatformString(struct soap*, struct condorCore__getPlatformString *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__getPlatformString(struct soap*, struct condorCore__getPlatformString *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__getPlatformString(struct soap*, const char*, int, const struct condorCore__getPlatformString *, const char*);
SOAP_FMAC3 struct condorCore__getPlatformString * SOAP_FMAC4 soap_get_condorCore__getPlatformString(struct soap*, struct condorCore__getPlatformString *, const char*, const char*);
SOAP_FMAC3 struct condorCore__getPlatformString * SOAP_FMAC4 soap_in_condorCore__getPlatformString(struct soap*, const char*, struct condorCore__getPlatformString *, const char*);

#ifndef SOAP_TYPE_condorCore__getPlatformStringResponse
#define SOAP_TYPE_condorCore__getPlatformStringResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__getPlatformStringResponse(struct soap*, struct condorCore__getPlatformStringResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__getPlatformStringResponse(struct soap*, const struct condorCore__getPlatformStringResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__getPlatformStringResponse(struct soap*, struct condorCore__getPlatformStringResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__getPlatformStringResponse(struct soap*, struct condorCore__getPlatformStringResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__getPlatformStringResponse(struct soap*, const char*, int, const struct condorCore__getPlatformStringResponse *, const char*);
SOAP_FMAC3 struct condorCore__getPlatformStringResponse * SOAP_FMAC4 soap_get_condorCore__getPlatformStringResponse(struct soap*, struct condorCore__getPlatformStringResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCore__getPlatformStringResponse * SOAP_FMAC4 soap_in_condorCore__getPlatformStringResponse(struct soap*, const char*, struct condorCore__getPlatformStringResponse *, const char*);

#ifndef SOAP_TYPE_condorCore__getVersionString
#define SOAP_TYPE_condorCore__getVersionString (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__getVersionString(struct soap*, struct condorCore__getVersionString const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__getVersionString(struct soap*, const struct condorCore__getVersionString *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__getVersionString(struct soap*, struct condorCore__getVersionString *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__getVersionString(struct soap*, struct condorCore__getVersionString *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__getVersionString(struct soap*, const char*, int, const struct condorCore__getVersionString *, const char*);
SOAP_FMAC3 struct condorCore__getVersionString * SOAP_FMAC4 soap_get_condorCore__getVersionString(struct soap*, struct condorCore__getVersionString *, const char*, const char*);
SOAP_FMAC3 struct condorCore__getVersionString * SOAP_FMAC4 soap_in_condorCore__getVersionString(struct soap*, const char*, struct condorCore__getVersionString *, const char*);

#ifndef SOAP_TYPE_condorCore__getVersionStringResponse
#define SOAP_TYPE_condorCore__getVersionStringResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__getVersionStringResponse(struct soap*, struct condorCore__getVersionStringResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__getVersionStringResponse(struct soap*, const struct condorCore__getVersionStringResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__getVersionStringResponse(struct soap*, struct condorCore__getVersionStringResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__getVersionStringResponse(struct soap*, struct condorCore__getVersionStringResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__getVersionStringResponse(struct soap*, const char*, int, const struct condorCore__getVersionStringResponse *, const char*);
SOAP_FMAC3 struct condorCore__getVersionStringResponse * SOAP_FMAC4 soap_get_condorCore__getVersionStringResponse(struct soap*, struct condorCore__getVersionStringResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCore__getVersionStringResponse * SOAP_FMAC4 soap_in_condorCore__getVersionStringResponse(struct soap*, const char*, struct condorCore__getVersionStringResponse *, const char*);

#ifndef SOAP_TYPE_condorCore__getInfoAd
#define SOAP_TYPE_condorCore__getInfoAd (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__getInfoAd(struct soap*, struct condorCore__getInfoAd const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__getInfoAd(struct soap*, const struct condorCore__getInfoAd *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__getInfoAd(struct soap*, struct condorCore__getInfoAd *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__getInfoAd(struct soap*, struct condorCore__getInfoAd *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__getInfoAd(struct soap*, const char*, int, const struct condorCore__getInfoAd *, const char*);
SOAP_FMAC3 struct condorCore__getInfoAd * SOAP_FMAC4 soap_get_condorCore__getInfoAd(struct soap*, struct condorCore__getInfoAd *, const char*, const char*);
SOAP_FMAC3 struct condorCore__getInfoAd * SOAP_FMAC4 soap_in_condorCore__getInfoAd(struct soap*, const char*, struct condorCore__getInfoAd *, const char*);

#ifndef SOAP_TYPE_condorCore__getInfoAdResponse
#define SOAP_TYPE_condorCore__getInfoAdResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__getInfoAdResponse(struct soap*, struct condorCore__getInfoAdResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__getInfoAdResponse(struct soap*, const struct condorCore__getInfoAdResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__getInfoAdResponse(struct soap*, struct condorCore__getInfoAdResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__getInfoAdResponse(struct soap*, struct condorCore__getInfoAdResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__getInfoAdResponse(struct soap*, const char*, int, const struct condorCore__getInfoAdResponse *, const char*);
SOAP_FMAC3 struct condorCore__getInfoAdResponse * SOAP_FMAC4 soap_get_condorCore__getInfoAdResponse(struct soap*, struct condorCore__getInfoAdResponse *, const char*, const char*);
SOAP_FMAC3 struct condorCore__getInfoAdResponse * SOAP_FMAC4 soap_in_condorCore__getInfoAdResponse(struct soap*, const char*, struct condorCore__getInfoAdResponse *, const char*);

#ifndef SOAP_TYPE_ClassAdStructArray
#define SOAP_TYPE_ClassAdStructArray (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ClassAdStructArray(struct soap*, struct ClassAdStructArray const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ClassAdStructArray(struct soap*, struct ClassAdStructArray const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ClassAdStructArray(struct soap*, struct ClassAdStructArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ClassAdStructArray(struct soap*, struct ClassAdStructArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ClassAdStructArray(struct soap*, const char*, int, const struct ClassAdStructArray *, const char*);
SOAP_FMAC3 struct ClassAdStructArray * SOAP_FMAC4 soap_get_ClassAdStructArray(struct soap*, struct ClassAdStructArray *, const char*, const char*);
SOAP_FMAC3 struct ClassAdStructArray * SOAP_FMAC4 soap_in_ClassAdStructArray(struct soap*, const char*, struct ClassAdStructArray *, const char*);

#ifndef SOAP_TYPE_ClassAdStruct
#define SOAP_TYPE_ClassAdStruct (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ClassAdStruct(struct soap*, struct ClassAdStruct const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ClassAdStruct(struct soap*, struct ClassAdStruct const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ClassAdStruct(struct soap*, struct ClassAdStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ClassAdStruct(struct soap*, struct ClassAdStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ClassAdStruct(struct soap*, const char*, int, const struct ClassAdStruct *, const char*);
SOAP_FMAC3 struct ClassAdStruct * SOAP_FMAC4 soap_get_ClassAdStruct(struct soap*, struct ClassAdStruct *, const char*, const char*);
SOAP_FMAC3 struct ClassAdStruct * SOAP_FMAC4 soap_in_ClassAdStruct(struct soap*, const char*, struct ClassAdStruct *, const char*);

#ifndef SOAP_TYPE_condorCore__ClassAdStructAttr
#define SOAP_TYPE_condorCore__ClassAdStructAttr (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__ClassAdStructAttr(struct soap*, const struct condorCore__ClassAdStructAttr *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__ClassAdStructAttr(struct soap*, const char*, int, const struct condorCore__ClassAdStructAttr *, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructAttr * SOAP_FMAC4 soap_get_condorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *, const char*, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructAttr * SOAP_FMAC4 soap_in_condorCore__ClassAdStructAttr(struct soap*, const char*, struct condorCore__ClassAdStructAttr *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_PointerToClassAdStruct
#define SOAP_TYPE_PointerToClassAdStruct (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToClassAdStruct(struct soap*, struct ClassAdStruct *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToClassAdStruct(struct soap*, struct ClassAdStruct *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToClassAdStruct(struct soap*, struct ClassAdStruct **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToClassAdStruct(struct soap*, struct ClassAdStruct **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToClassAdStruct(struct soap*, const char *, int, struct ClassAdStruct *const*, const char *);
SOAP_FMAC3 struct ClassAdStruct ** SOAP_FMAC4 soap_get_PointerToClassAdStruct(struct soap*, struct ClassAdStruct **, const char*, const char*);
SOAP_FMAC3 struct ClassAdStruct ** SOAP_FMAC4 soap_in_PointerToClassAdStruct(struct soap*, const char*, struct ClassAdStruct **, const char*);

#ifndef SOAP_TYPE_PointerTocondorCore__ClassAdStructAttr
#define SOAP_TYPE_PointerTocondorCore__ClassAdStructAttr (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocondorCore__ClassAdStructAttr(struct soap*, const char *, int, struct condorCore__ClassAdStructAttr *const*, const char *);
SOAP_FMAC3 struct condorCore__ClassAdStructAttr ** SOAP_FMAC4 soap_get_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr **, const char*, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructAttr ** SOAP_FMAC4 soap_in_PointerTocondorCore__ClassAdStructAttr(struct soap*, const char*, struct condorCore__ClassAdStructAttr **, const char*);

#ifndef SOAP_TYPE_PointerTobool
#define SOAP_TYPE_PointerTobool (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTobool(struct soap*, bool *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTobool(struct soap*, bool *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTobool(struct soap*, bool **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTobool(struct soap*, bool **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTobool(struct soap*, const char *, int, bool *const*, const char *);
SOAP_FMAC3 bool ** SOAP_FMAC4 soap_get_PointerTobool(struct soap*, bool **, const char*, const char*);
SOAP_FMAC3 bool ** SOAP_FMAC4 soap_in_PointerTobool(struct soap*, const char*, bool **, const char*);

#ifndef SOAP_TYPE_PointerTofloat
#define SOAP_TYPE_PointerTofloat (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofloat(struct soap*, float *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTofloat(struct soap*, float *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTofloat(struct soap*, float **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofloat(struct soap*, float **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofloat(struct soap*, const char *, int, float *const*, const char *);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_get_PointerTofloat(struct soap*, float **, const char*, const char*);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_in_PointerTofloat(struct soap*, const char*, float **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToint(struct soap*, int **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anyURI(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(soap_collector)

#endif

/* end of soap_collectorH.h */
