/* soap_collectorStub.h
   Generated by gSOAP 2.5.2 from gsoap_collector.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#ifndef soap_collectorStub_H
#define soap_collectorStub_H
#include "stdsoap2.h"

SOAP_BEGIN_NAMESPACE(soap_collector)

/* Enumerations */

#ifndef _SOAP_condorCore__StatusCode
#define _SOAP_condorCore__StatusCode
enum condorCore__StatusCode {SUCCESS = 0, FAIL = 1, INVALIDTRANSACTION = 2, UNKNOWNJOB = 3, UNKNOWNFILE = 4, INCOMPLETE = 5, INVALIDOFFSET = 6, ALREADYEXISTS = 7};
#endif

#ifndef _SOAP_condorCore__ClassAdAttrType
#define _SOAP_condorCore__ClassAdAttrType
enum condorCore__ClassAdAttrType {INTEGER = 110, FLOAT = 102, STRING = 115, EXPRESSION = 120, BOOL = 98, UNDEFINED = 117, ERROR = 101};
#endif

/* Classes and Structs */

/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
};

/* condorCore:Status: */
struct condorCore__Status
{
	enum condorCore__StatusCode code;
	char *message;
	struct condorCore__Status *next;
};

/* condorCore:ClassAdStructAttr: */
struct condorCore__ClassAdStructAttr
{
	char *name;
	enum condorCore__ClassAdAttrType type;
	char *value;
};

/* Array of condorCore:ClassAdStruct schema type: */
struct condorCore__ClassAdStruct
{
	struct condorCore__ClassAdStructAttr *__ptr;
	int __size;
};

/* Array of condorCore:ClassAdStructArray schema type: */
struct condorCore__ClassAdStructArray
{
	struct condorCore__ClassAdStruct *__ptr;
	int __size;
};

/* condorCore:ClassAdStructAndStatus: */
struct condorCore__ClassAdStructAndStatus
{
	struct condorCore__Status status;
	struct condorCore__ClassAdStruct classAd;
};

/* condorCore:ClassAdStructArrayAndStatus: */
struct condorCore__ClassAdStructArrayAndStatus
{
	struct condorCore__Status status;
	struct condorCore__ClassAdStructArray classAdArray;
};

/* condorCore:StringAndStatus: */
struct condorCore__StringAndStatus
{
	struct condorCore__Status status;
	char *message;
};

/* condorCollector:queryStartdAdsResponse: */
struct condorCollector__queryStartdAdsResponse
{
	struct condorCore__ClassAdStructArray result;	/* return */
};

/* condorCollector:queryStartdAds: */
struct condorCollector__queryStartdAds
{
	char *constraint;
};

/* condorCollector:queryScheddAdsResponse: */
struct condorCollector__queryScheddAdsResponse
{
	struct condorCore__ClassAdStructArray result;	/* return */
};

/* condorCollector:queryScheddAds: */
struct condorCollector__queryScheddAds
{
	char *constraint;
};

/* condorCollector:queryMasterAdsResponse: */
struct condorCollector__queryMasterAdsResponse
{
	struct condorCore__ClassAdStructArray result;	/* return */
};

/* condorCollector:queryMasterAds: */
struct condorCollector__queryMasterAds
{
	char *constraint;
};

/* condorCollector:querySubmittorAdsResponse: */
struct condorCollector__querySubmittorAdsResponse
{
	struct condorCore__ClassAdStructArray result;	/* return */
};

/* condorCollector:querySubmittorAds: */
struct condorCollector__querySubmittorAds
{
	char *constraint;
};

/* condorCollector:queryLicenseAdsResponse: */
struct condorCollector__queryLicenseAdsResponse
{
	struct condorCore__ClassAdStructArray result;	/* return */
};

/* condorCollector:queryLicenseAds: */
struct condorCollector__queryLicenseAds
{
	char *constraint;
};

/* condorCollector:queryStorageAdsResponse: */
struct condorCollector__queryStorageAdsResponse
{
	struct condorCore__ClassAdStructArray result;	/* return */
};

/* condorCollector:queryStorageAds: */
struct condorCollector__queryStorageAds
{
	char *constraint;
};

/* condorCollector:queryAnyAdsResponse: */
struct condorCollector__queryAnyAdsResponse
{
	struct condorCore__ClassAdStructArray result;	/* return */
};

/* condorCollector:queryAnyAds: */
struct condorCollector__queryAnyAds
{
	char *constraint;
};

/* SOAP Header: */
struct SOAP_ENV__Header
{
	void *dummy;	/* transient */
};

/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;
	char *SOAP_ENV__Node;
	char *SOAP_ENV__Role;
};

/* SOAP-ENV:Detail: */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <value> */
	void *value;	/* transient */
	char *__any;
};

/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;
	char *faultstring;
	char *faultactor;
	struct SOAP_ENV__Detail *detail;
	struct SOAP_ENV__Code *SOAP_ENV__Code;
	char *SOAP_ENV__Reason;
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};

/* Types With Custom (De)serializers: */

/* Typedefs */
typedef char *_XML;
typedef char *_QName;
typedef char *xsd__string;
typedef char *xsd__anyURI;
typedef float xsd__float;
typedef int xsd__int;
typedef bool xsd__boolean;
typedef LONG64 xsd__long;
typedef char xsd__byte;

/* Extern */

/* Remote Methods */

SOAP_FMAC5 int SOAP_FMAC6 condorCollector__queryStartdAds(struct soap*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 condorCollector__queryScheddAds(struct soap*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 condorCollector__queryMasterAds(struct soap*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 condorCollector__querySubmittorAds(struct soap*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 condorCollector__queryLicenseAds(struct soap*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 condorCollector__queryStorageAds(struct soap*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 condorCollector__queryAnyAds(struct soap*, char *, struct condorCore__ClassAdStructArray &);

/* Stubs */

SOAP_FMAC5 int SOAP_FMAC6 soap_call_condorCollector__queryStartdAds(struct soap*, const char*, const char*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_condorCollector__queryScheddAds(struct soap*, const char*, const char*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_condorCollector__queryMasterAds(struct soap*, const char*, const char*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_condorCollector__querySubmittorAds(struct soap*, const char*, const char*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_condorCollector__queryLicenseAds(struct soap*, const char*, const char*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_condorCollector__queryStorageAds(struct soap*, const char*, const char*, char *, struct condorCore__ClassAdStructArray &);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_condorCollector__queryAnyAds(struct soap*, const char*, const char*, char *, struct condorCore__ClassAdStructArray &);

/* Skeletons */

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_condorCollector__queryStartdAds(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_condorCollector__queryScheddAds(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_condorCollector__queryMasterAds(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_condorCollector__querySubmittorAds(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_condorCollector__queryLicenseAds(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_condorCollector__queryStorageAds(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_condorCollector__queryAnyAds(struct soap*);

SOAP_END_NAMESPACE(soap_collector)

#endif

/* end of soap_collectorStub.h */
