#!/bin/sh

#cleanup old code
rm -f *.cpp
rm -f *.h

##################################################
for i in `ls ../../../condor_tt/*.c`;
do
ln -s $i `echo ${i##*/}pp`;
done

for i in `ls ../../../condor_tt/*.cpp`;
do
ln -s $i `echo ${i##*/}`;
done

for i in `ls ../../../condor_tt/*.h`;
do
ln -s $i `echo ${i##*/}`;
done
