#!/bin/sh

##################################################
for i in `ls ../../../condor_collector.V6/*`;
do

#cleanup old softlinks
rm -f `echo ${i##*/}`

if [ ${i#*.} == "c" ]; then
	ln -s $i `echo ${i##*/}pp`;
elif [ ${i##*/} != "Imakefile" ] ; then
	ln -s $i `echo ${i##*/}`;
fi

done

