#!/bin/sh

rm -f `find . | grep [.]h`
rmdir utils

# link in the normal includes
for i in `ls ../../condor_includes/*.h`; 
do 
ln -s $i `echo ${i##*/}`;
done

mkdir utils 

#link in the util include under the utils location
for i in `ls ../../condor_c++_util/*.h`;
do
ln -s ../$i ./utils/`echo ${i##*/}`;
done

