#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


# For this test, we don't submit a Condor job at all. Instead, we create a
# place for the checkpoint to be stored, start up the dmtcp_coordinator on a
# random port, and do the work to checkpoint the job. Then we verify that the
# output is what it is supposed to be.

print "Running stubbed DMTCP test for job_ckpt_combo-sanity_dmtcp\n";

exit 0;

$testdesc =  'Printer Test - DMTCP';
$testname = "job_ckpt_combo-sanity_dmtcp";
$results = 'job_ckpt_combo-sanity_dmtcp.results';

# locations and binaries of dmtcp;
$dmtcp_dir = "./dmtcp-local";

$sandbox = ".";

# XXX This test needs to be completed.
