#!/bin/sh

CONDOR_PROCNO=$CONDOR_PROCNO
CONDOR_NPROCS=$CONDOR_NPROCS
CONDOR_REMOTE_SPOOL_DIR=$CONDOR_REMOTE_SPOOL_DIR

chmod 755 sshd.sh
chmod 755 condor_ssh

. sshd.sh $CONDOR_PROCNO $CONDOR_NPROCS 

# If not the head node, just sleep forever, to let the
# sshds run
if [ $CONDOR_PROCNO -ne 0 ]
then
		wait
		sshd_cleanup
fi

EXECUTABLE=$1

# the binary is copied but the executable flag is cleared.
# so the script have to take care of this
chmod +x $EXECUTABLE

#LAMDIR=/u/g/t/gthain/lam/bin
LAMDIR=/u/g/t/gthain/lam-7.0.6/bin
PATH=$LAMDIR:$PATH
export PATH

# to allow multiple lam jobs running on a single machine,
# we have to give somewhat unique value
export LAM_MPI_SESSION_SUFFIX=$$

# This is the way to accomplish the above when running 
# LAM < 7.0.2
export LAM_MPI_SOCKET_SUFFIX=$$

export LAMRSH=./condor_ssh

# when a job is killed by the user, this script will get sigterm
# This script have to catch it and do the cleaning for the
# lam environment
finalize()
{
sshd_cleanup
lamhalt
exit
}
trap finalize TERM

CONDOR_CONTACT_FILE=contact
export CONDOR_CONTACT_FILE

# The second field in the contact file is the machine name
# that condor_ssh knows how to use
awk '{print $2}' < $CONDOR_CONTACT_FILE >> machines


# start the lam environment
lamboot -ssi boot rsh machines

if [ $? -ne 0 ]
then
	echo "lamscript error booting lam"
	exit 1
fi

## run the actual mpijob
mpirun C $EXECUTABLE $@ &

CHILD=$!
TMP=130
while [ $TMP -gt 128 ] ; do
	wait $CHILD
	TMP=$?;
done

# clean up files
sshd_cleanup
/bin/rm -f machines

# clean up lam
lamhalt

exit $TMP
