#!/bin/sh

# start a ProcD that will monitor this process
#
if [ "$0" != `basename "$0"` ]
then
	DIR=`dirname "$0"`
	if [ -x "$DIR/procd" ]
	then
		PROCD="$DIR/procd"
	fi
fi
if [ -z "$PROCD" ]
then
	PROCD=procd
fi
$PROCD $$

# now just exec what we were asked to
#
exec "$@"
