/* soap_scheddH.h
   Generated by gSOAP 2.5.2 from gsoap_schedd.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under the gSOAP public license and GPL.
   See README.txt for further details.
*/
#ifndef soap_scheddH_H
#define soap_scheddH_H
#include "soap_scheddStub.h"

SOAP_BEGIN_NAMESPACE(soap_schedd)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putattachments(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getattachments(struct soap*);

#ifndef SOAP_TYPE_xsd__byte
#define SOAP_TYPE_xsd__byte (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_xsd__byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_xsd__byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_long(struct soap*, long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_long(struct soap*, long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_long(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_long(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__long(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__long(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_xsd__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_xsd__long(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_LONG64(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_xsd__float
#define SOAP_TYPE_xsd__float (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__float(struct soap*, float *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__float(struct soap*, float const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_xsd__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_xsd__float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_float(struct soap*, float const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedByte(struct soap*, unsigned char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedInt(struct soap*, unsigned int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_condorSchedd__UniverseType
#define SOAP_TYPE_condorSchedd__UniverseType (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__UniverseType(struct soap*, enum condorSchedd__UniverseType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__UniverseType(struct soap*, enum condorSchedd__UniverseType const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__UniverseType(struct soap*, enum condorSchedd__UniverseType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__UniverseType(struct soap*, const char*, int, const enum condorSchedd__UniverseType *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_condorSchedd__UniverseType2s(struct soap*, enum condorSchedd__UniverseType);
SOAP_FMAC3 enum condorSchedd__UniverseType * SOAP_FMAC4 soap_get_condorSchedd__UniverseType(struct soap*, enum condorSchedd__UniverseType *, const char*, const char*);
SOAP_FMAC3 enum condorSchedd__UniverseType * SOAP_FMAC4 soap_in_condorSchedd__UniverseType(struct soap*, const char*, enum condorSchedd__UniverseType *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2condorSchedd__UniverseType(struct soap*, const char*, enum condorSchedd__UniverseType *);

#ifndef SOAP_TYPE_condorSchedd__HashType
#define SOAP_TYPE_condorSchedd__HashType (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__HashType(struct soap*, enum condorSchedd__HashType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__HashType(struct soap*, enum condorSchedd__HashType const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__HashType(struct soap*, enum condorSchedd__HashType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__HashType(struct soap*, const char*, int, const enum condorSchedd__HashType *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_condorSchedd__HashType2s(struct soap*, enum condorSchedd__HashType);
SOAP_FMAC3 enum condorSchedd__HashType * SOAP_FMAC4 soap_get_condorSchedd__HashType(struct soap*, enum condorSchedd__HashType *, const char*, const char*);
SOAP_FMAC3 enum condorSchedd__HashType * SOAP_FMAC4 soap_in_condorSchedd__HashType(struct soap*, const char*, enum condorSchedd__HashType *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2condorSchedd__HashType(struct soap*, const char*, enum condorSchedd__HashType *);

#ifndef SOAP_TYPE_condorCore__ClassAdAttrType
#define SOAP_TYPE_condorCore__ClassAdAttrType (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__ClassAdAttrType(struct soap*, enum condorCore__ClassAdAttrType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__ClassAdAttrType(struct soap*, enum condorCore__ClassAdAttrType const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__ClassAdAttrType(struct soap*, enum condorCore__ClassAdAttrType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__ClassAdAttrType(struct soap*, const char*, int, const enum condorCore__ClassAdAttrType *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_condorCore__ClassAdAttrType2s(struct soap*, enum condorCore__ClassAdAttrType);
SOAP_FMAC3 enum condorCore__ClassAdAttrType * SOAP_FMAC4 soap_get_condorCore__ClassAdAttrType(struct soap*, enum condorCore__ClassAdAttrType *, const char*, const char*);
SOAP_FMAC3 enum condorCore__ClassAdAttrType * SOAP_FMAC4 soap_in_condorCore__ClassAdAttrType(struct soap*, const char*, enum condorCore__ClassAdAttrType *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2condorCore__ClassAdAttrType(struct soap*, const char*, enum condorCore__ClassAdAttrType *);

#ifndef SOAP_TYPE_condorCore__StatusCode
#define SOAP_TYPE_condorCore__StatusCode (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__StatusCode(struct soap*, enum condorCore__StatusCode *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__StatusCode(struct soap*, enum condorCore__StatusCode const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__StatusCode(struct soap*, enum condorCore__StatusCode *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__StatusCode(struct soap*, const char*, int, const enum condorCore__StatusCode *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_condorCore__StatusCode2s(struct soap*, enum condorCore__StatusCode);
SOAP_FMAC3 enum condorCore__StatusCode * SOAP_FMAC4 soap_get_condorCore__StatusCode(struct soap*, enum condorCore__StatusCode *, const char*, const char*);
SOAP_FMAC3 enum condorCore__StatusCode * SOAP_FMAC4 soap_in_condorCore__StatusCode(struct soap*, const char*, enum condorCore__StatusCode *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2condorCore__StatusCode(struct soap*, const char*, enum condorCore__StatusCode *);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__boolean(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_xsd__boolean2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2xsd__boolean(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_bool(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2bool(struct soap*, const char*, bool *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (101)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (100)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (99)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (98)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_condorSchedd__createJobTemplate
#define SOAP_TYPE_condorSchedd__createJobTemplate (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__createJobTemplate(struct soap*, struct condorSchedd__createJobTemplate const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__createJobTemplate(struct soap*, const struct condorSchedd__createJobTemplate *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__createJobTemplate(struct soap*, struct condorSchedd__createJobTemplate *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__createJobTemplate(struct soap*, struct condorSchedd__createJobTemplate *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__createJobTemplate(struct soap*, const char*, int, const struct condorSchedd__createJobTemplate *, const char*);
SOAP_FMAC3 struct condorSchedd__createJobTemplate * SOAP_FMAC4 soap_get_condorSchedd__createJobTemplate(struct soap*, struct condorSchedd__createJobTemplate *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__createJobTemplate * SOAP_FMAC4 soap_in_condorSchedd__createJobTemplate(struct soap*, const char*, struct condorSchedd__createJobTemplate *, const char*);

#ifndef SOAP_TYPE_condorSchedd__discoverDagRequirements
#define SOAP_TYPE_condorSchedd__discoverDagRequirements (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__discoverDagRequirements(struct soap*, struct condorSchedd__discoverDagRequirements const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__discoverDagRequirements(struct soap*, const struct condorSchedd__discoverDagRequirements *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__discoverDagRequirements(struct soap*, struct condorSchedd__discoverDagRequirements *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__discoverDagRequirements(struct soap*, struct condorSchedd__discoverDagRequirements *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__discoverDagRequirements(struct soap*, const char*, int, const struct condorSchedd__discoverDagRequirements *, const char*);
SOAP_FMAC3 struct condorSchedd__discoverDagRequirements * SOAP_FMAC4 soap_get_condorSchedd__discoverDagRequirements(struct soap*, struct condorSchedd__discoverDagRequirements *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__discoverDagRequirements * SOAP_FMAC4 soap_in_condorSchedd__discoverDagRequirements(struct soap*, const char*, struct condorSchedd__discoverDagRequirements *, const char*);

#ifndef SOAP_TYPE_condorSchedd__discoverJobRequirements
#define SOAP_TYPE_condorSchedd__discoverJobRequirements (91)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__discoverJobRequirements(struct soap*, struct condorSchedd__discoverJobRequirements const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__discoverJobRequirements(struct soap*, const struct condorSchedd__discoverJobRequirements *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__discoverJobRequirements(struct soap*, struct condorSchedd__discoverJobRequirements *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__discoverJobRequirements(struct soap*, struct condorSchedd__discoverJobRequirements *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__discoverJobRequirements(struct soap*, const char*, int, const struct condorSchedd__discoverJobRequirements *, const char*);
SOAP_FMAC3 struct condorSchedd__discoverJobRequirements * SOAP_FMAC4 soap_get_condorSchedd__discoverJobRequirements(struct soap*, struct condorSchedd__discoverJobRequirements *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__discoverJobRequirements * SOAP_FMAC4 soap_in_condorSchedd__discoverJobRequirements(struct soap*, const char*, struct condorSchedd__discoverJobRequirements *, const char*);

#ifndef SOAP_TYPE_condorSchedd__getFile
#define SOAP_TYPE_condorSchedd__getFile (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__getFile(struct soap*, struct condorSchedd__getFile const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__getFile(struct soap*, const struct condorSchedd__getFile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__getFile(struct soap*, struct condorSchedd__getFile *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__getFile(struct soap*, struct condorSchedd__getFile *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__getFile(struct soap*, const char*, int, const struct condorSchedd__getFile *, const char*);
SOAP_FMAC3 struct condorSchedd__getFile * SOAP_FMAC4 soap_get_condorSchedd__getFile(struct soap*, struct condorSchedd__getFile *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__getFile * SOAP_FMAC4 soap_in_condorSchedd__getFile(struct soap*, const char*, struct condorSchedd__getFile *, const char*);

#ifndef SOAP_TYPE_condorSchedd__sendFile
#define SOAP_TYPE_condorSchedd__sendFile (86)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__sendFile(struct soap*, struct condorSchedd__sendFile const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__sendFile(struct soap*, const struct condorSchedd__sendFile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__sendFile(struct soap*, struct condorSchedd__sendFile *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__sendFile(struct soap*, struct condorSchedd__sendFile *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__sendFile(struct soap*, const char*, int, const struct condorSchedd__sendFile *, const char*);
SOAP_FMAC3 struct condorSchedd__sendFile * SOAP_FMAC4 soap_get_condorSchedd__sendFile(struct soap*, struct condorSchedd__sendFile *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__sendFile * SOAP_FMAC4 soap_in_condorSchedd__sendFile(struct soap*, const char*, struct condorSchedd__sendFile *, const char*);

#ifndef SOAP_TYPE_condorSchedd__declareFile
#define SOAP_TYPE_condorSchedd__declareFile (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__declareFile(struct soap*, struct condorSchedd__declareFile const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__declareFile(struct soap*, const struct condorSchedd__declareFile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__declareFile(struct soap*, struct condorSchedd__declareFile *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__declareFile(struct soap*, struct condorSchedd__declareFile *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__declareFile(struct soap*, const char*, int, const struct condorSchedd__declareFile *, const char*);
SOAP_FMAC3 struct condorSchedd__declareFile * SOAP_FMAC4 soap_get_condorSchedd__declareFile(struct soap*, struct condorSchedd__declareFile *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__declareFile * SOAP_FMAC4 soap_in_condorSchedd__declareFile(struct soap*, const char*, struct condorSchedd__declareFile *, const char*);

#ifndef SOAP_TYPE_condorSchedd__getJobAd
#define SOAP_TYPE_condorSchedd__getJobAd (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__getJobAd(struct soap*, struct condorSchedd__getJobAd const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__getJobAd(struct soap*, const struct condorSchedd__getJobAd *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__getJobAd(struct soap*, struct condorSchedd__getJobAd *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__getJobAd(struct soap*, struct condorSchedd__getJobAd *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__getJobAd(struct soap*, const char*, int, const struct condorSchedd__getJobAd *, const char*);
SOAP_FMAC3 struct condorSchedd__getJobAd * SOAP_FMAC4 soap_get_condorSchedd__getJobAd(struct soap*, struct condorSchedd__getJobAd *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__getJobAd * SOAP_FMAC4 soap_in_condorSchedd__getJobAd(struct soap*, const char*, struct condorSchedd__getJobAd *, const char*);

#ifndef SOAP_TYPE_condorSchedd__getJobAds
#define SOAP_TYPE_condorSchedd__getJobAds (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__getJobAds(struct soap*, struct condorSchedd__getJobAds const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__getJobAds(struct soap*, const struct condorSchedd__getJobAds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__getJobAds(struct soap*, struct condorSchedd__getJobAds *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__getJobAds(struct soap*, struct condorSchedd__getJobAds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__getJobAds(struct soap*, const char*, int, const struct condorSchedd__getJobAds *, const char*);
SOAP_FMAC3 struct condorSchedd__getJobAds * SOAP_FMAC4 soap_get_condorSchedd__getJobAds(struct soap*, struct condorSchedd__getJobAds *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__getJobAds * SOAP_FMAC4 soap_in_condorSchedd__getJobAds(struct soap*, const char*, struct condorSchedd__getJobAds *, const char*);

#ifndef SOAP_TYPE_condorSchedd__submit
#define SOAP_TYPE_condorSchedd__submit (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__submit(struct soap*, struct condorSchedd__submit const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__submit(struct soap*, const struct condorSchedd__submit *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__submit(struct soap*, struct condorSchedd__submit *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__submit(struct soap*, struct condorSchedd__submit *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__submit(struct soap*, const char*, int, const struct condorSchedd__submit *, const char*);
SOAP_FMAC3 struct condorSchedd__submit * SOAP_FMAC4 soap_get_condorSchedd__submit(struct soap*, struct condorSchedd__submit *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__submit * SOAP_FMAC4 soap_in_condorSchedd__submit(struct soap*, const char*, struct condorSchedd__submit *, const char*);

#ifndef SOAP_TYPE_condorSchedd__releaseJob
#define SOAP_TYPE_condorSchedd__releaseJob (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__releaseJob(struct soap*, struct condorSchedd__releaseJob const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__releaseJob(struct soap*, const struct condorSchedd__releaseJob *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__releaseJob(struct soap*, struct condorSchedd__releaseJob *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__releaseJob(struct soap*, struct condorSchedd__releaseJob *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__releaseJob(struct soap*, const char*, int, const struct condorSchedd__releaseJob *, const char*);
SOAP_FMAC3 struct condorSchedd__releaseJob * SOAP_FMAC4 soap_get_condorSchedd__releaseJob(struct soap*, struct condorSchedd__releaseJob *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__releaseJob * SOAP_FMAC4 soap_in_condorSchedd__releaseJob(struct soap*, const char*, struct condorSchedd__releaseJob *, const char*);

#ifndef SOAP_TYPE_condorSchedd__holdJob
#define SOAP_TYPE_condorSchedd__holdJob (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__holdJob(struct soap*, struct condorSchedd__holdJob const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__holdJob(struct soap*, const struct condorSchedd__holdJob *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__holdJob(struct soap*, struct condorSchedd__holdJob *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__holdJob(struct soap*, struct condorSchedd__holdJob *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__holdJob(struct soap*, const char*, int, const struct condorSchedd__holdJob *, const char*);
SOAP_FMAC3 struct condorSchedd__holdJob * SOAP_FMAC4 soap_get_condorSchedd__holdJob(struct soap*, struct condorSchedd__holdJob *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__holdJob * SOAP_FMAC4 soap_in_condorSchedd__holdJob(struct soap*, const char*, struct condorSchedd__holdJob *, const char*);

#ifndef SOAP_TYPE_condorSchedd__removeJob
#define SOAP_TYPE_condorSchedd__removeJob (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__removeJob(struct soap*, struct condorSchedd__removeJob const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__removeJob(struct soap*, const struct condorSchedd__removeJob *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__removeJob(struct soap*, struct condorSchedd__removeJob *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__removeJob(struct soap*, struct condorSchedd__removeJob *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__removeJob(struct soap*, const char*, int, const struct condorSchedd__removeJob *, const char*);
SOAP_FMAC3 struct condorSchedd__removeJob * SOAP_FMAC4 soap_get_condorSchedd__removeJob(struct soap*, struct condorSchedd__removeJob *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__removeJob * SOAP_FMAC4 soap_in_condorSchedd__removeJob(struct soap*, const char*, struct condorSchedd__removeJob *, const char*);

#ifndef SOAP_TYPE_condorSchedd__newJob
#define SOAP_TYPE_condorSchedd__newJob (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__newJob(struct soap*, struct condorSchedd__newJob const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__newJob(struct soap*, const struct condorSchedd__newJob *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__newJob(struct soap*, struct condorSchedd__newJob *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__newJob(struct soap*, struct condorSchedd__newJob *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__newJob(struct soap*, const char*, int, const struct condorSchedd__newJob *, const char*);
SOAP_FMAC3 struct condorSchedd__newJob * SOAP_FMAC4 soap_get_condorSchedd__newJob(struct soap*, struct condorSchedd__newJob *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__newJob * SOAP_FMAC4 soap_in_condorSchedd__newJob(struct soap*, const char*, struct condorSchedd__newJob *, const char*);

#ifndef SOAP_TYPE_condorSchedd__removeCluster
#define SOAP_TYPE_condorSchedd__removeCluster (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__removeCluster(struct soap*, struct condorSchedd__removeCluster const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__removeCluster(struct soap*, const struct condorSchedd__removeCluster *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__removeCluster(struct soap*, struct condorSchedd__removeCluster *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__removeCluster(struct soap*, struct condorSchedd__removeCluster *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__removeCluster(struct soap*, const char*, int, const struct condorSchedd__removeCluster *, const char*);
SOAP_FMAC3 struct condorSchedd__removeCluster * SOAP_FMAC4 soap_get_condorSchedd__removeCluster(struct soap*, struct condorSchedd__removeCluster *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__removeCluster * SOAP_FMAC4 soap_in_condorSchedd__removeCluster(struct soap*, const char*, struct condorSchedd__removeCluster *, const char*);

#ifndef SOAP_TYPE_condorSchedd__newCluster
#define SOAP_TYPE_condorSchedd__newCluster (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__newCluster(struct soap*, struct condorSchedd__newCluster const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__newCluster(struct soap*, const struct condorSchedd__newCluster *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__newCluster(struct soap*, struct condorSchedd__newCluster *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__newCluster(struct soap*, struct condorSchedd__newCluster *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__newCluster(struct soap*, const char*, int, const struct condorSchedd__newCluster *, const char*);
SOAP_FMAC3 struct condorSchedd__newCluster * SOAP_FMAC4 soap_get_condorSchedd__newCluster(struct soap*, struct condorSchedd__newCluster *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__newCluster * SOAP_FMAC4 soap_in_condorSchedd__newCluster(struct soap*, const char*, struct condorSchedd__newCluster *, const char*);

#ifndef SOAP_TYPE_condorSchedd__extendTransaction
#define SOAP_TYPE_condorSchedd__extendTransaction (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__extendTransaction(struct soap*, struct condorSchedd__extendTransaction const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__extendTransaction(struct soap*, const struct condorSchedd__extendTransaction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__extendTransaction(struct soap*, struct condorSchedd__extendTransaction *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__extendTransaction(struct soap*, struct condorSchedd__extendTransaction *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__extendTransaction(struct soap*, const char*, int, const struct condorSchedd__extendTransaction *, const char*);
SOAP_FMAC3 struct condorSchedd__extendTransaction * SOAP_FMAC4 soap_get_condorSchedd__extendTransaction(struct soap*, struct condorSchedd__extendTransaction *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__extendTransaction * SOAP_FMAC4 soap_in_condorSchedd__extendTransaction(struct soap*, const char*, struct condorSchedd__extendTransaction *, const char*);

#ifndef SOAP_TYPE_condorSchedd__abortTransaction
#define SOAP_TYPE_condorSchedd__abortTransaction (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__abortTransaction(struct soap*, struct condorSchedd__abortTransaction const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__abortTransaction(struct soap*, const struct condorSchedd__abortTransaction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__abortTransaction(struct soap*, struct condorSchedd__abortTransaction *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__abortTransaction(struct soap*, struct condorSchedd__abortTransaction *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__abortTransaction(struct soap*, const char*, int, const struct condorSchedd__abortTransaction *, const char*);
SOAP_FMAC3 struct condorSchedd__abortTransaction * SOAP_FMAC4 soap_get_condorSchedd__abortTransaction(struct soap*, struct condorSchedd__abortTransaction *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__abortTransaction * SOAP_FMAC4 soap_in_condorSchedd__abortTransaction(struct soap*, const char*, struct condorSchedd__abortTransaction *, const char*);

#ifndef SOAP_TYPE_condorSchedd__commitTransaction
#define SOAP_TYPE_condorSchedd__commitTransaction (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__commitTransaction(struct soap*, struct condorSchedd__commitTransaction const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__commitTransaction(struct soap*, const struct condorSchedd__commitTransaction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__commitTransaction(struct soap*, struct condorSchedd__commitTransaction *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__commitTransaction(struct soap*, struct condorSchedd__commitTransaction *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__commitTransaction(struct soap*, const char*, int, const struct condorSchedd__commitTransaction *, const char*);
SOAP_FMAC3 struct condorSchedd__commitTransaction * SOAP_FMAC4 soap_get_condorSchedd__commitTransaction(struct soap*, struct condorSchedd__commitTransaction *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__commitTransaction * SOAP_FMAC4 soap_in_condorSchedd__commitTransaction(struct soap*, const char*, struct condorSchedd__commitTransaction *, const char*);

#ifndef SOAP_TYPE_condorSchedd__beginTransaction
#define SOAP_TYPE_condorSchedd__beginTransaction (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__beginTransaction(struct soap*, struct condorSchedd__beginTransaction const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__beginTransaction(struct soap*, const struct condorSchedd__beginTransaction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__beginTransaction(struct soap*, struct condorSchedd__beginTransaction *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__beginTransaction(struct soap*, struct condorSchedd__beginTransaction *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__beginTransaction(struct soap*, const char*, int, const struct condorSchedd__beginTransaction *, const char*);
SOAP_FMAC3 struct condorSchedd__beginTransaction * SOAP_FMAC4 soap_get_condorSchedd__beginTransaction(struct soap*, struct condorSchedd__beginTransaction *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__beginTransaction * SOAP_FMAC4 soap_in_condorSchedd__beginTransaction(struct soap*, const char*, struct condorSchedd__beginTransaction *, const char*);

#ifndef SOAP_TYPE_condorSchedd__Base64DataAndStatusResponse
#define SOAP_TYPE_condorSchedd__Base64DataAndStatusResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__Base64DataAndStatusResponse(struct soap*, struct condorSchedd__Base64DataAndStatusResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__Base64DataAndStatusResponse(struct soap*, const struct condorSchedd__Base64DataAndStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__Base64DataAndStatusResponse(struct soap*, struct condorSchedd__Base64DataAndStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__Base64DataAndStatusResponse(struct soap*, struct condorSchedd__Base64DataAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__Base64DataAndStatusResponse(struct soap*, const char*, int, const struct condorSchedd__Base64DataAndStatusResponse *, const char*);
SOAP_FMAC3 struct condorSchedd__Base64DataAndStatusResponse * SOAP_FMAC4 soap_get_condorSchedd__Base64DataAndStatusResponse(struct soap*, struct condorSchedd__Base64DataAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__Base64DataAndStatusResponse * SOAP_FMAC4 soap_in_condorSchedd__Base64DataAndStatusResponse(struct soap*, const char*, struct condorSchedd__Base64DataAndStatusResponse *, const char*);

#ifndef SOAP_TYPE_condorSchedd__ClassAdStructAndStatusResponse
#define SOAP_TYPE_condorSchedd__ClassAdStructAndStatusResponse (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__ClassAdStructAndStatusResponse(struct soap*, struct condorSchedd__ClassAdStructAndStatusResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__ClassAdStructAndStatusResponse(struct soap*, const struct condorSchedd__ClassAdStructAndStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__ClassAdStructAndStatusResponse(struct soap*, struct condorSchedd__ClassAdStructAndStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__ClassAdStructAndStatusResponse(struct soap*, struct condorSchedd__ClassAdStructAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__ClassAdStructAndStatusResponse(struct soap*, const char*, int, const struct condorSchedd__ClassAdStructAndStatusResponse *, const char*);
SOAP_FMAC3 struct condorSchedd__ClassAdStructAndStatusResponse * SOAP_FMAC4 soap_get_condorSchedd__ClassAdStructAndStatusResponse(struct soap*, struct condorSchedd__ClassAdStructAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__ClassAdStructAndStatusResponse * SOAP_FMAC4 soap_in_condorSchedd__ClassAdStructAndStatusResponse(struct soap*, const char*, struct condorSchedd__ClassAdStructAndStatusResponse *, const char*);

#ifndef SOAP_TYPE_condorSchedd__ClassAdStructArrayAndStatusResponse
#define SOAP_TYPE_condorSchedd__ClassAdStructArrayAndStatusResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__ClassAdStructArrayAndStatusResponse(struct soap*, struct condorSchedd__ClassAdStructArrayAndStatusResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__ClassAdStructArrayAndStatusResponse(struct soap*, const struct condorSchedd__ClassAdStructArrayAndStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__ClassAdStructArrayAndStatusResponse(struct soap*, struct condorSchedd__ClassAdStructArrayAndStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__ClassAdStructArrayAndStatusResponse(struct soap*, struct condorSchedd__ClassAdStructArrayAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__ClassAdStructArrayAndStatusResponse(struct soap*, const char*, int, const struct condorSchedd__ClassAdStructArrayAndStatusResponse *, const char*);
SOAP_FMAC3 struct condorSchedd__ClassAdStructArrayAndStatusResponse * SOAP_FMAC4 soap_get_condorSchedd__ClassAdStructArrayAndStatusResponse(struct soap*, struct condorSchedd__ClassAdStructArrayAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__ClassAdStructArrayAndStatusResponse * SOAP_FMAC4 soap_in_condorSchedd__ClassAdStructArrayAndStatusResponse(struct soap*, const char*, struct condorSchedd__ClassAdStructArrayAndStatusResponse *, const char*);

#ifndef SOAP_TYPE_condorSchedd__RequirementsAndStatusResponse
#define SOAP_TYPE_condorSchedd__RequirementsAndStatusResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__RequirementsAndStatusResponse(struct soap*, struct condorSchedd__RequirementsAndStatusResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__RequirementsAndStatusResponse(struct soap*, const struct condorSchedd__RequirementsAndStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__RequirementsAndStatusResponse(struct soap*, struct condorSchedd__RequirementsAndStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__RequirementsAndStatusResponse(struct soap*, struct condorSchedd__RequirementsAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__RequirementsAndStatusResponse(struct soap*, const char*, int, const struct condorSchedd__RequirementsAndStatusResponse *, const char*);
SOAP_FMAC3 struct condorSchedd__RequirementsAndStatusResponse * SOAP_FMAC4 soap_get_condorSchedd__RequirementsAndStatusResponse(struct soap*, struct condorSchedd__RequirementsAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__RequirementsAndStatusResponse * SOAP_FMAC4 soap_in_condorSchedd__RequirementsAndStatusResponse(struct soap*, const char*, struct condorSchedd__RequirementsAndStatusResponse *, const char*);

#ifndef SOAP_TYPE_condorSchedd__IntAndStatusResponse
#define SOAP_TYPE_condorSchedd__IntAndStatusResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__IntAndStatusResponse(struct soap*, struct condorSchedd__IntAndStatusResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__IntAndStatusResponse(struct soap*, const struct condorSchedd__IntAndStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__IntAndStatusResponse(struct soap*, struct condorSchedd__IntAndStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__IntAndStatusResponse(struct soap*, struct condorSchedd__IntAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__IntAndStatusResponse(struct soap*, const char*, int, const struct condorSchedd__IntAndStatusResponse *, const char*);
SOAP_FMAC3 struct condorSchedd__IntAndStatusResponse * SOAP_FMAC4 soap_get_condorSchedd__IntAndStatusResponse(struct soap*, struct condorSchedd__IntAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__IntAndStatusResponse * SOAP_FMAC4 soap_in_condorSchedd__IntAndStatusResponse(struct soap*, const char*, struct condorSchedd__IntAndStatusResponse *, const char*);

#ifndef SOAP_TYPE_condorSchedd__TransactionAndStatusResponse
#define SOAP_TYPE_condorSchedd__TransactionAndStatusResponse (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__TransactionAndStatusResponse(struct soap*, struct condorSchedd__TransactionAndStatusResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__TransactionAndStatusResponse(struct soap*, const struct condorSchedd__TransactionAndStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__TransactionAndStatusResponse(struct soap*, struct condorSchedd__TransactionAndStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__TransactionAndStatusResponse(struct soap*, struct condorSchedd__TransactionAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__TransactionAndStatusResponse(struct soap*, const char*, int, const struct condorSchedd__TransactionAndStatusResponse *, const char*);
SOAP_FMAC3 struct condorSchedd__TransactionAndStatusResponse * SOAP_FMAC4 soap_get_condorSchedd__TransactionAndStatusResponse(struct soap*, struct condorSchedd__TransactionAndStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__TransactionAndStatusResponse * SOAP_FMAC4 soap_in_condorSchedd__TransactionAndStatusResponse(struct soap*, const char*, struct condorSchedd__TransactionAndStatusResponse *, const char*);

#ifndef SOAP_TYPE_condorSchedd__StatusResponse
#define SOAP_TYPE_condorSchedd__StatusResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__StatusResponse(struct soap*, struct condorSchedd__StatusResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__StatusResponse(struct soap*, const struct condorSchedd__StatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__StatusResponse(struct soap*, struct condorSchedd__StatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__StatusResponse(struct soap*, struct condorSchedd__StatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__StatusResponse(struct soap*, const char*, int, const struct condorSchedd__StatusResponse *, const char*);
SOAP_FMAC3 struct condorSchedd__StatusResponse * SOAP_FMAC4 soap_get_condorSchedd__StatusResponse(struct soap*, struct condorSchedd__StatusResponse *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__StatusResponse * SOAP_FMAC4 soap_in_condorSchedd__StatusResponse(struct soap*, const char*, struct condorSchedd__StatusResponse *, const char*);

#ifndef SOAP_TYPE_condorSchedd__Base64DataAndStatus
#define SOAP_TYPE_condorSchedd__Base64DataAndStatus (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__Base64DataAndStatus(struct soap*, struct condorSchedd__Base64DataAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__Base64DataAndStatus(struct soap*, const struct condorSchedd__Base64DataAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__Base64DataAndStatus(struct soap*, struct condorSchedd__Base64DataAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__Base64DataAndStatus(struct soap*, struct condorSchedd__Base64DataAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__Base64DataAndStatus(struct soap*, const char*, int, const struct condorSchedd__Base64DataAndStatus *, const char*);
SOAP_FMAC3 struct condorSchedd__Base64DataAndStatus * SOAP_FMAC4 soap_get_condorSchedd__Base64DataAndStatus(struct soap*, struct condorSchedd__Base64DataAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__Base64DataAndStatus * SOAP_FMAC4 soap_in_condorSchedd__Base64DataAndStatus(struct soap*, const char*, struct condorSchedd__Base64DataAndStatus *, const char*);

#ifndef SOAP_TYPE_condorSchedd__IntAndStatus
#define SOAP_TYPE_condorSchedd__IntAndStatus (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__IntAndStatus(struct soap*, struct condorSchedd__IntAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__IntAndStatus(struct soap*, const struct condorSchedd__IntAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__IntAndStatus(struct soap*, struct condorSchedd__IntAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__IntAndStatus(struct soap*, struct condorSchedd__IntAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__IntAndStatus(struct soap*, const char*, int, const struct condorSchedd__IntAndStatus *, const char*);
SOAP_FMAC3 struct condorSchedd__IntAndStatus * SOAP_FMAC4 soap_get_condorSchedd__IntAndStatus(struct soap*, struct condorSchedd__IntAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__IntAndStatus * SOAP_FMAC4 soap_in_condorSchedd__IntAndStatus(struct soap*, const char*, struct condorSchedd__IntAndStatus *, const char*);

#ifndef SOAP_TYPE_condorSchedd__TransactionAndStatus
#define SOAP_TYPE_condorSchedd__TransactionAndStatus (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__TransactionAndStatus(struct soap*, struct condorSchedd__TransactionAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__TransactionAndStatus(struct soap*, const struct condorSchedd__TransactionAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__TransactionAndStatus(struct soap*, struct condorSchedd__TransactionAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__TransactionAndStatus(struct soap*, struct condorSchedd__TransactionAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__TransactionAndStatus(struct soap*, const char*, int, const struct condorSchedd__TransactionAndStatus *, const char*);
SOAP_FMAC3 struct condorSchedd__TransactionAndStatus * SOAP_FMAC4 soap_get_condorSchedd__TransactionAndStatus(struct soap*, struct condorSchedd__TransactionAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__TransactionAndStatus * SOAP_FMAC4 soap_in_condorSchedd__TransactionAndStatus(struct soap*, const char*, struct condorSchedd__TransactionAndStatus *, const char*);

#ifndef SOAP_TYPE_condorSchedd__RequirementsAndStatus
#define SOAP_TYPE_condorSchedd__RequirementsAndStatus (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__RequirementsAndStatus(struct soap*, struct condorSchedd__RequirementsAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__RequirementsAndStatus(struct soap*, const struct condorSchedd__RequirementsAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__RequirementsAndStatus(struct soap*, struct condorSchedd__RequirementsAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__RequirementsAndStatus(struct soap*, struct condorSchedd__RequirementsAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__RequirementsAndStatus(struct soap*, const char*, int, const struct condorSchedd__RequirementsAndStatus *, const char*);
SOAP_FMAC3 struct condorSchedd__RequirementsAndStatus * SOAP_FMAC4 soap_get_condorSchedd__RequirementsAndStatus(struct soap*, struct condorSchedd__RequirementsAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__RequirementsAndStatus * SOAP_FMAC4 soap_in_condorSchedd__RequirementsAndStatus(struct soap*, const char*, struct condorSchedd__RequirementsAndStatus *, const char*);

#ifndef SOAP_TYPE_condorSchedd__Requirements
#define SOAP_TYPE_condorSchedd__Requirements (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__Requirements(struct soap*, struct condorSchedd__Requirements const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__Requirements(struct soap*, struct condorSchedd__Requirements const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__Requirements(struct soap*, struct condorSchedd__Requirements *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__Requirements(struct soap*, struct condorSchedd__Requirements *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__Requirements(struct soap*, const char*, int, const struct condorSchedd__Requirements *, const char*);
SOAP_FMAC3 struct condorSchedd__Requirements * SOAP_FMAC4 soap_get_condorSchedd__Requirements(struct soap*, struct condorSchedd__Requirements *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__Requirements * SOAP_FMAC4 soap_in_condorSchedd__Requirements(struct soap*, const char*, struct condorSchedd__Requirements *, const char*);

#ifndef SOAP_TYPE_condorSchedd__Transaction
#define SOAP_TYPE_condorSchedd__Transaction (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__Transaction(struct soap*, struct condorSchedd__Transaction const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__Transaction(struct soap*, const struct condorSchedd__Transaction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__Transaction(struct soap*, struct condorSchedd__Transaction *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__Transaction(struct soap*, struct condorSchedd__Transaction *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__Transaction(struct soap*, const char*, int, const struct condorSchedd__Transaction *, const char*);
SOAP_FMAC3 struct condorSchedd__Transaction * SOAP_FMAC4 soap_get_condorSchedd__Transaction(struct soap*, struct condorSchedd__Transaction *, const char*, const char*);
SOAP_FMAC3 struct condorSchedd__Transaction * SOAP_FMAC4 soap_in_condorSchedd__Transaction(struct soap*, const char*, struct condorSchedd__Transaction *, const char*);

#ifndef SOAP_TYPE_condorCore__StringAndStatus
#define SOAP_TYPE_condorCore__StringAndStatus (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__StringAndStatus(struct soap*, struct condorCore__StringAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__StringAndStatus(struct soap*, const struct condorCore__StringAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__StringAndStatus(struct soap*, struct condorCore__StringAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__StringAndStatus(struct soap*, struct condorCore__StringAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__StringAndStatus(struct soap*, const char*, int, const struct condorCore__StringAndStatus *, const char*);
SOAP_FMAC3 struct condorCore__StringAndStatus * SOAP_FMAC4 soap_get_condorCore__StringAndStatus(struct soap*, struct condorCore__StringAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condorCore__StringAndStatus * SOAP_FMAC4 soap_in_condorCore__StringAndStatus(struct soap*, const char*, struct condorCore__StringAndStatus *, const char*);

#ifndef SOAP_TYPE_condorCore__ClassAdStructArrayAndStatus
#define SOAP_TYPE_condorCore__ClassAdStructArrayAndStatus (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__ClassAdStructArrayAndStatus(struct soap*, struct condorCore__ClassAdStructArrayAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__ClassAdStructArrayAndStatus(struct soap*, const struct condorCore__ClassAdStructArrayAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__ClassAdStructArrayAndStatus(struct soap*, struct condorCore__ClassAdStructArrayAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__ClassAdStructArrayAndStatus(struct soap*, struct condorCore__ClassAdStructArrayAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__ClassAdStructArrayAndStatus(struct soap*, const char*, int, const struct condorCore__ClassAdStructArrayAndStatus *, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructArrayAndStatus * SOAP_FMAC4 soap_get_condorCore__ClassAdStructArrayAndStatus(struct soap*, struct condorCore__ClassAdStructArrayAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructArrayAndStatus * SOAP_FMAC4 soap_in_condorCore__ClassAdStructArrayAndStatus(struct soap*, const char*, struct condorCore__ClassAdStructArrayAndStatus *, const char*);

#ifndef SOAP_TYPE_condorCore__ClassAdStructAndStatus
#define SOAP_TYPE_condorCore__ClassAdStructAndStatus (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__ClassAdStructAndStatus(struct soap*, struct condorCore__ClassAdStructAndStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__ClassAdStructAndStatus(struct soap*, const struct condorCore__ClassAdStructAndStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__ClassAdStructAndStatus(struct soap*, struct condorCore__ClassAdStructAndStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__ClassAdStructAndStatus(struct soap*, struct condorCore__ClassAdStructAndStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__ClassAdStructAndStatus(struct soap*, const char*, int, const struct condorCore__ClassAdStructAndStatus *, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructAndStatus * SOAP_FMAC4 soap_get_condorCore__ClassAdStructAndStatus(struct soap*, struct condorCore__ClassAdStructAndStatus *, const char*, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructAndStatus * SOAP_FMAC4 soap_in_condorCore__ClassAdStructAndStatus(struct soap*, const char*, struct condorCore__ClassAdStructAndStatus *, const char*);

#ifndef SOAP_TYPE_condorCore__ClassAdStructArray
#define SOAP_TYPE_condorCore__ClassAdStructArray (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__ClassAdStructArray(struct soap*, struct condorCore__ClassAdStructArray const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__ClassAdStructArray(struct soap*, struct condorCore__ClassAdStructArray const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__ClassAdStructArray(struct soap*, struct condorCore__ClassAdStructArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__ClassAdStructArray(struct soap*, struct condorCore__ClassAdStructArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__ClassAdStructArray(struct soap*, const char*, int, const struct condorCore__ClassAdStructArray *, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructArray * SOAP_FMAC4 soap_get_condorCore__ClassAdStructArray(struct soap*, struct condorCore__ClassAdStructArray *, const char*, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructArray * SOAP_FMAC4 soap_in_condorCore__ClassAdStructArray(struct soap*, const char*, struct condorCore__ClassAdStructArray *, const char*);

#ifndef SOAP_TYPE_condorCore__ClassAdStruct
#define SOAP_TYPE_condorCore__ClassAdStruct (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__ClassAdStruct(struct soap*, const char*, int, const struct condorCore__ClassAdStruct *, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStruct * SOAP_FMAC4 soap_get_condorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct *, const char*, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStruct * SOAP_FMAC4 soap_in_condorCore__ClassAdStruct(struct soap*, const char*, struct condorCore__ClassAdStruct *, const char*);

#ifndef SOAP_TYPE_condorCore__ClassAdStructAttr
#define SOAP_TYPE_condorCore__ClassAdStructAttr (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__ClassAdStructAttr(struct soap*, const struct condorCore__ClassAdStructAttr *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__ClassAdStructAttr(struct soap*, const char*, int, const struct condorCore__ClassAdStructAttr *, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructAttr * SOAP_FMAC4 soap_get_condorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *, const char*, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructAttr * SOAP_FMAC4 soap_in_condorCore__ClassAdStructAttr(struct soap*, const char*, struct condorCore__ClassAdStructAttr *, const char*);

#ifndef SOAP_TYPE_condorCore__Status
#define SOAP_TYPE_condorCore__Status (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorCore__Status(struct soap*, struct condorCore__Status const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorCore__Status(struct soap*, const struct condorCore__Status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorCore__Status(struct soap*, struct condorCore__Status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorCore__Status(struct soap*, struct condorCore__Status *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorCore__Status(struct soap*, const char*, int, const struct condorCore__Status *, const char*);
SOAP_FMAC3 struct condorCore__Status * SOAP_FMAC4 soap_get_condorCore__Status(struct soap*, struct condorCore__Status *, const char*, const char*);
SOAP_FMAC3 struct condorCore__Status * SOAP_FMAC4 soap_in_condorCore__Status(struct soap*, const char*, struct condorCore__Status *, const char*);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (103)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (102)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToxsd__base64Binary
#define SOAP_TYPE_PointerToxsd__base64Binary (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__base64Binary(struct soap*, const char *, int, struct xsd__base64Binary *const*, const char *);
SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_get_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary **, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_in_PointerToxsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary **, const char*);

#ifndef SOAP_TYPE_PointerTocondorSchedd__Requirement
#define SOAP_TYPE_PointerTocondorSchedd__Requirement (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocondorSchedd__Requirement(struct soap*, char **const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTocondorSchedd__Requirement(struct soap*, char **const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTocondorSchedd__Requirement(struct soap*, char ***);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocondorSchedd__Requirement(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocondorSchedd__Requirement(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTocondorSchedd__Requirement(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTocondorSchedd__Requirement(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_condorSchedd__Requirement
#define SOAP_TYPE_condorSchedd__Requirement (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_condorSchedd__Requirement(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_condorSchedd__Requirement(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_condorSchedd__Requirement(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_condorSchedd__Requirement(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_condorSchedd__Requirement(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_condorSchedd__Requirement(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_condorSchedd__Requirement(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_PointerTocondorCore__ClassAdStruct
#define SOAP_TYPE_PointerTocondorCore__ClassAdStruct (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocondorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTocondorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTocondorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocondorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocondorCore__ClassAdStruct(struct soap*, const char *, int, struct condorCore__ClassAdStruct *const*, const char *);
SOAP_FMAC3 struct condorCore__ClassAdStruct ** SOAP_FMAC4 soap_get_PointerTocondorCore__ClassAdStruct(struct soap*, struct condorCore__ClassAdStruct **, const char*, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStruct ** SOAP_FMAC4 soap_in_PointerTocondorCore__ClassAdStruct(struct soap*, const char*, struct condorCore__ClassAdStruct **, const char*);

#ifndef SOAP_TYPE_PointerTocondorCore__ClassAdStructAttr
#define SOAP_TYPE_PointerTocondorCore__ClassAdStructAttr (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocondorCore__ClassAdStructAttr(struct soap*, const char *, int, struct condorCore__ClassAdStructAttr *const*, const char *);
SOAP_FMAC3 struct condorCore__ClassAdStructAttr ** SOAP_FMAC4 soap_get_PointerTocondorCore__ClassAdStructAttr(struct soap*, struct condorCore__ClassAdStructAttr **, const char*, const char*);
SOAP_FMAC3 struct condorCore__ClassAdStructAttr ** SOAP_FMAC4 soap_in_PointerTocondorCore__ClassAdStructAttr(struct soap*, const char*, struct condorCore__ClassAdStructAttr **, const char*);

#ifndef SOAP_TYPE_PointerTocondorCore__Status
#define SOAP_TYPE_PointerTocondorCore__Status (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTocondorCore__Status(struct soap*, struct condorCore__Status *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTocondorCore__Status(struct soap*, struct condorCore__Status *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTocondorCore__Status(struct soap*, struct condorCore__Status **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTocondorCore__Status(struct soap*, struct condorCore__Status **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTocondorCore__Status(struct soap*, const char *, int, struct condorCore__Status *const*, const char *);
SOAP_FMAC3 struct condorCore__Status ** SOAP_FMAC4 soap_get_PointerTocondorCore__Status(struct soap*, struct condorCore__Status **, const char*, const char*);
SOAP_FMAC3 struct condorCore__Status ** SOAP_FMAC4 soap_in_PointerTocondorCore__Status(struct soap*, const char*, struct condorCore__Status **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTounsignedByte(struct soap*, unsigned char **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anyURI(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(soap_schedd)

#endif

/* end of soap_scheddH.h */
