DROP TABLE cdb_users;
DROP TABLE transfers;
DROP TABLE files CASCADE;
DROP TABLE fileusages;
DROP SEQUENCE condor_seqfileid;
DROP TABLE machines_vertical;
DROP TABLE machines_vertical_history;
DROP TABLE machines_horizontal CASCADE;
DROP TABLE machines_horizontal_history CASCADE;
DROP TABLE clusterads_vertical CASCADE;
DROP TABLE clusterads_horizontal CASCADE;
DROP TABLE procads_vertical CASCADE;
DROP TABLE procads_horizontal CASCADE;
DROP TABLE jobs_vertical_history CASCADE;
DROP TABLE jobs_horizontal_History CASCADE;
DROP TABLE runs CASCADE;
DROP SEQUENCE seqrunid;
DROP TABLE rejects;
DROP TABLE matches;
DROP VIEW agg_user_jobs_waiting;
DROP VIEW agg_user_jobs_held;
DROP VIEW agg_user_jobs_running;
DROP VIEW agg_user_jobs_fin_last_day;
DROP TABLE l_jobstatus;
DROP TABLE throwns;
DROP TABLE events;
DROP TABLE l_eventtype;
DROP TABLE genericmessages;
DROP TABLE jobqueuepollinginfo CASCADE;
DROP TABLE currencies;
DROP TABLE daemons_horizontal;
DROP TABLE daemons_horizontal_history;
DROP TABLE daemons_vertical;
DROP TABLE daemons_vertical_history;
DROP TABLE submitters_horizontal;
DROP TABLE submitters_horizontal_history;
DROP VIEW history_jobs_flocked_in;
DROP VIEW current_jobs_flocked_in;
DROP VIEW history_jobs_flocked_out;
DROP VIEW current_jobs_flocked_out;
DROP TABLE dummy_single_row_table;
DROP TABLE error_sqllogs CASCADE;
DROP TABLE history_jobs_to_purge;
DROP TABLE quilldbmonitor;
DROP TABLE quill_schema_version;
DROP TABLE maintenance_log;
DROP FUNCTION quill_purgehistory(resourceHistoryDuration integer, runHistoryDuration integer, jobHistoryDuration integer);
