DROP TABLE cdb_users;
DROP TABLE transfers;
DROP TABLE files CASCADE;
DROP TABLE fileusages;
DROP SEQUENCE condor_seqfileid;
DROP TABLE machine;
DROP TABLE machine_history;
DROP TABLE machine_classad CASCADE;
DROP TABLE machine_classad_history CASCADE;
DROP TABLE ClusterAds_Vertical CASCADE;
DROP TABLE ClusterAds_Horizontal CASCADE;
DROP TABLE ProcAds_Vertical CASCADE;
DROP TABLE ProcAds_Horizontal CASCADE;
DROP TABLE History_Vertical CASCADE;
DROP TABLE History_Horizontal CASCADE;
DROP TABLE Runs CASCADE;
DROP SEQUENCE SeqRunId;
DROP TABLE Rejects;
DROP TABLE Matches;
DROP VIEW AGG_User_Jobs_Waiting;
DROP VIEW AGG_User_Jobs_Held;
DROP VIEW AGG_User_Jobs_Running;
DROP VIEW AGG_User_Jobs_Fin_Last_Day;
DROP TABLE L_Jobstatus;
DROP TABLE thrown;
DROP TABLE events;
DROP TABLE L_eventType;
DROP TABLE Generic;
DROP TABLE JobQueuePollingInfo CASCADE;
DROP TABLE Currency;
DROP TABLE Daemon_Horizontal;
DROP TABLE Daemon_Horizontal_History;
DROP TABLE Daemon_Vertical;
DROP TABLE Daemon_Vertical_History;
DROP TABLE Schedd_Horizontal;
DROP TABLE Schedd_Vertical;
DROP TABLE Schedd_Horizontal_History;
DROP TABLE Schedd_Vertical_History;
DROP TABLE Master_Vertical;
DROP TABLE Master_Vertical_History;
DROP TABLE Negotiator_Vertical;
DROP TABLE Negotiator_Vertical_History;
DROP VIEW HISTORY_JOBS_FLOCKED_IN;
DROP VIEW CURRENT_JOBS_FLOCKED_IN;
DROP VIEW History_JOBS_FLOCKED_OUT;
DROP VIEW CURRENT_JOBS_FLOCKED_OUT;
DROP TABLE dummy_single_row_table;
