DROP TABLE cdb_users;
DROP TABLE transfers;
DROP TABLE files CASCADE;
DROP TABLE fileusages;
DROP SEQUENCE condor_seqfileid;
DROP TABLE machines_vertical;
DROP TABLE machines_vertical_history;
DROP TABLE machines_horizontal CASCADE;
DROP TABLE machines_horizontal_history CASCADE;
DROP TABLE ClusterAds_Vertical CASCADE;
DROP TABLE ClusterAds_Horizontal CASCADE;
DROP TABLE ProcAds_Vertical CASCADE;
DROP TABLE ProcAds_Horizontal CASCADE;
DROP TABLE Jobs_Vertical_History CASCADE;
DROP TABLE Jobs_Horizontal_History CASCADE;
DROP TABLE Runs CASCADE;
DROP SEQUENCE SeqRunId;
DROP TABLE Rejects;
DROP TABLE Matches;
DROP VIEW AGG_User_Jobs_Waiting;
DROP VIEW AGG_User_Jobs_Held;
DROP VIEW AGG_User_Jobs_Running;
DROP VIEW AGG_User_Jobs_Fin_Last_Day;
DROP TABLE L_Jobstatus;
DROP TABLE throwns;
DROP TABLE events;
DROP TABLE L_eventType;
DROP TABLE GenericMessages;
DROP TABLE JobQueuePollingInfo CASCADE;
DROP TABLE Currencies;
DROP TABLE Daemons_Horizontal;
DROP TABLE Daemons_Horizontal_History;
DROP TABLE Daemons_Vertical;
DROP TABLE Daemons_Vertical_History;
DROP TABLE Submitters_Horizontal;
DROP TABLE Submitters_Horizontal_History;
DROP VIEW HISTORY_JOBS_FLOCKED_IN;
DROP VIEW CURRENT_JOBS_FLOCKED_IN;
DROP VIEW History_JOBS_FLOCKED_OUT;
DROP VIEW CURRENT_JOBS_FLOCKED_OUT;
DROP TABLE dummy_single_row_table;
DROP TABLE Error_Sqllogs CASCADE;
DROP FUNCTION quill_purgeHistory(resourceHistoryDuration integer, runHistoryDuration integer, jobHistoryDuration integer);
DROP TABLE History_Jobs_To_Purge;
DROP TABLE quillDBMonitor;
DROP TABLE quill_schema_version;
DROP TABLE maintenance_log;
